eclipse-che/che-devfile-registry

- .htaccess
- Dockerfile
- Dockerfile.rhel
- build.sh
- cico_build.sh
- deploy/kubernetes/che-devfile-registry/Chart.yaml
- deploy/kubernetes/che-devfile-registry/README.md
- deploy/kubernetes/che-devfile-registry/templates/deployment.yaml
- deploy/kubernetes/che-devfile-registry/templates/ingress.yaml
- deploy/kubernetes/che-devfile-registry/templates/service.yaml
- deploy/kubernetes/che-devfile-registry/values.yaml
- deploy/openshift/che-devfile-registry.yaml
- devfiles/.htaccess
- devfiles/che7-preview.yaml
- index.sh
Initialize Che Devfile Registry. Changes are divided into separate commits to make review easier:
1. Add Che 7 Preview Devfile based on the corresponding stack.
Note that devfile in repository contains extra fields (description, displayName, icon) which are copied to index.json and dropped out from devfile on phase of build.
2. Add an ability to build image for Che Devfile Registry.
3. Set up CentOS CI. It contains build script and job will be created after merging this PR. 
4. Add template for deploying Che Devfile Registry to OpenShift.
5. Add helm chart for deploying Che Devfile Registry on Kubernetes.
https://github.com/eclipse/che/issues/13353
This is only first PR for setting up Che Devfile Registry and the following changes will be set soon:
- set up circleci to perform bash …
> Initialize Che Devfile Registry

- devfiles/apache-camel-springboot-che7/meta.yaml
- devfiles/dotnet/meta.yaml
- devfiles/go/meta.yaml
- devfiles/java-gradle/meta.yaml
- devfiles/java-maven/meta.yaml
- devfiles/python/meta.yaml
- index.sh
This PR follows the following discussion https://github.com/eclipse/che-devfile-registry/pull/3#discussion_r287310042
and it adds tags to meta.yaml.
Values are copied/pasted from existing Che 7 stacks from Che Repository.
https://github.com/eclipse/che/issues/13353
> Add tags to meta.yaml

- devfiles/java-maven/devfile.yaml
Since OpenShift starts containers with a random UID (which has no username associated with it), maven running on OpenShift cannot figure out where to place the .m2 repository. This PR explicitly sets the -Duser.home parameter to /home/user to match the mounted .m2 volume.
https://github.com/eclipse/che/issues/13451
> Specify home path in java-maven devfile

- devfiles/apache-camel-springboot-che7/devfile.yaml
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Since we have defined memory limit in [plugin description](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml#L16), we don't need to do that in devfile.
This PR should be merged after https://github.com/openshiftio/saas-openshiftio/pull/1308
https://github.com/eclipse/che/issues/13225
> Remove memory limit of apache-camel plugin

- devfiles/nodejs/devfile.yaml
- devfiles/nodejs/meta.yaml
Add a new nodjes stack with an hello-world express web application
https://github.com/eclipse/che/issues/12620
> Add a nodejs stack

- devfiles/java-gradle/devfile.yaml
Modifies the volume used for the `.gradle` directory to be `/home/gradle/.gradle`. This is necessary because the [dockerfile](https://github.com/keeganwitt/docker-gradle/blob/7c606d205bcf13551f8203e12174c37004383694/jdk8/Dockerfile#L17) used specifies this as a `VOLUME`, which causes issues when that path is not mounted via PVC.
I have tested this devfile and it appears to work (at least, as well as community docker images generally do -- see https://github.com/eclipse/che/issues/13454) but further testing is appreciated.
https://github.com/eclipse/che/issues/13384, see [comment](https://github.com/eclipse/che/issues/13384#issuecomment-503175239) for more explanation.
> Update gradle mounted volume path to match dockerfile

- devfiles/angular/devfile.yaml
- devfiles/angular/meta.yaml
Add AngularJS devfile along with sample project.
Initially, there was `test` command but I removed this since it requires `CHROME BIN` and maybe this is not even enough to run tests inside a container. I'll create a separate issue to improve this devfile after merging this PR.
> Add AngularJS devfile along with sample project

- devfiles/nodejs-mongo/devfile.yaml
- devfiles/nodejs-mongo/meta.yaml
Adds a stack with nodejs and mongodb with an example application.
Current problems:
* the application started through the command seems to stop after a couple of minutes (this seems to be an issue with Che or even K8s in general?)
* The example curl command to create a user is stuck and generates no response. I didn't find the root cause for this yet.
> Add a mongo db application stack.

- devfiles/angular/meta.yaml
- devfiles/apache-camel-springboot/meta.yaml
- devfiles/dotnet/meta.yaml
- devfiles/go/meta.yaml
- devfiles/java-gradle/meta.yaml
- devfiles/java-maven/meta.yaml
- devfiles/nodejs-mongo/meta.yaml
- devfiles/nodejs/meta.yaml
- devfiles/php-laravel/meta.yaml
- devfiles/php-mysql/meta.yaml
- devfiles/php-symfony/meta.yaml
- devfiles/php-web-simple/meta.yaml
- devfiles/python-django/meta.yaml
- devfiles/python/meta.yaml
Clean up of meta files for default stacks
https://github.com/eclipse/che/issues/13592
> Clarify names of default stacks

- devfiles/nodejs-react/devfile.yaml
- devfiles/nodejs-react/meta.yaml
Adds NodeJS stack with the react realworld example [1]
1. It is not possible to use `registry.access.redhat.com/ubi8/nodejs-10` image due to error `system limit for number of file watchers reached` when server starts (`npm start`).
2. `API_ROOT` [2] can't be modified due to issue [3]
[1] https://github.com/gothinkster/react-redux-realworld-example-app
[2] https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/src/agent.js#L6
[3] https://github.com/gothinkster/react-redux-realworld-example-app/issues/134
> Add NodeJS stack with react realworld app

- arbitrary-users-patch/Dockerfile
- arbitrary-users-patch/base_images
- arbitrary-users-patch/build_images.sh
- arbitrary-users-patch/entrypoint.sh
Adding Che 7 community images with the support of arbitrary user to make them OpenShift compatible.
`build_images.sh` will build images with arbitrary user support which is required for running on OpenShift e.g.
`quay.io/eclipse-che/che7-python-centos:latest`
The next step would be automating pushing those images to the `https://quay.io/organization/eclipse-che` during the CI build. My idea was to reuse `cico_build.sh` [1] and make the image build / push process part of the main CI [2]. This should be pretty easy to accomplish assuming that CI bot with `{QUAY_USERNAME}` [3] will have push rights to the `https://quay.io/organization/eclipse-che` which is not the case atm (I believe we would need to grant write access to the bot and ask SD to apply those permissions to allow pushing not …
> che #13454 Adding Che 7 java 11 community images with support of arbitrary user to make them OpenShift compatible

- cico_build.sh
Pushing rhel images to 'quay.io/openshiftio' and centos images to 'quay.io/eclipse-che' during the CI build
https://github.com/eclipse/che/issues/13813
Should be merged only once dedicated cico job pr is merged - https://github.com/openshiftio/openshiftio-cico-jobs/pull/1035
> che #13813: Pushing rhel images to 'quay.io/openshiftio' and centos images to 'quay.io/eclipse-che' during the CI build

- cico_build.sh
che #13813: Pushing centos images to 'eclipse' org (not 'eclipse-che') on quay.io
It was decided to consolidate all the community images in a single  https://quay.io/organization/eclipse organization
https://github.com/eclipse/che/issues/13813
> che #13813: Pushing centos images to 'eclipse' org on quay.io

- README.md
Cosmetic fix in Readme to trigger the build - https://ci.centos.org/job/devtools-che-devfile-registry-build-master/
Looks like the repo should have been pre-created beforehand - https://quay.io/repository/eclipse/che-devfile-registry
related to https://github.com/eclipse/che/issues/13813
> Cosmetic fix in Readme

- cico_build_nightly.sh
Adding a separate script for the nightly ci build
https://github.com/eclipse/che/issues/13813 
the second part of the issue - `Update che-devfile-registry-periodic CentOS CI job to build the devfile registry image (centos only) and tag it as nightly`
> che #13813: Adding script for the nightly ci build

- cico_build_nightly.sh
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
che #13813: Adding missing REGISTRY env var to the nightly ci build
> che #13813: Adding missing REGISTRY env var to the nightly ci build

- devfiles/java-mysql/devfile.yaml
- devfiles/java-mysql/meta.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-spring/meta.yaml
- devfiles/java-web-vertx/devfile.yaml
- devfiles/java-web-vertx/meta.yaml
This PR adds the following samples devfiles:
| | stack | sample |
|-| ----- | ------ |
| :heavy_check_mark: | java-spring-web | https://github.com/che-samples/web-java-spring.git |
| :heavy_check_mark: | java-vertx | https://github.com/vert-x3/vertx-examples |
| :heavy_check_mark: | java-mysql | https://github.com/che-samples/web-java-spring-petclinic |
Notes:
* initially java-postgresql was requested but we do not have (and did not find easily) Java + PostgreSQL sample, and was decided to replace it with stack that we used to have `JAVA + MYSQL`
* Initially, sample from https://github.com/vert-x3/vertx-examples was requested but Devfile do not support `keepDirectory` feature and it was decided to use our old https://github.com/che-samples/web-java-vertx. Also, note that verx container is …
> Add Java Web devfiles

- cico_build_nightly.sh
Fixes a mistake breaking the nightly build -- we attempt to push before logging into the eclipse quay repo.
> Build and push patched images *after* logging in

- README.md
- build.sh
- cico_build.sh
- deploy/kubernetes/che-devfile-registry/values.yaml
- deploy/openshift/che-devfile-registry.yaml
Some leftover of https://github.com/eclipse/che-devfile-registry/pull/33 and https://github.com/eclipse/che-devfile-registry/pull/35
Related to milestone 7.0.0 issue https://github.com/eclipse/che/issues/13813
> Fix some references to quay.io/openshiftio repository

- devfiles/python-django/devfile.yaml
* django application was forked into [1]
* `ptsvd` [2] injected into the sources [3].
* added task to run server in debug mode
* added configuration to debug django app remotely 
https://github.com/eclipse/che/issues/13816
[1] https://github.com/che-samples/django-realworld-example-app
[2] https://pypi.org/project/ptvsd/
[3] https://github.com/che-samples/django-realworld-example-app/blob/master/manage.py#L8-L11
> Add task to debug django app remotely

- deploy/kubernetes/che-devfile-registry/templates/deployment.yaml
Signed-off-by: Michal Vala <mvala@redhat.com>
fix helm chart deployment config
https://github.com/eclipse/che/pull/13890
> fix helm chart deployment strategy config

- arbitrary-users-patch/Dockerfile
- arbitrary-users-patch/entrypoint.sh
- devfiles/java-mysql/devfile.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-vertx/devfile.yaml
- Update the arbitrary users patch to make sure $HOME is always writable,
fixing issues with some images.
- Update `java-spring`, `java-mysql`, and `java-vertx` to use patched images
- Update the commands in these images since maven wrapper is incompatible with community maven image
- The base image used for these stacks is **changed** in this PR: we use `maven:3.6.1-jdk-8` instead of `registry.centos.org/che-stacks/centos-jdk8` to avoid building another patched image.
One change this makes for the spring images is changing the command to **not** use the maven wrapper. This wrapper is intended to make it easier to use maven (https://github.com/takari/maven-wrapper/) but appears to not be necessary for the image we are using. Additionally the wrapper is incompatible with the maven …
> Update dockerfile patch and make new java devfiles used patched images

- arbitrary-users-patch/base_images
- devfiles/angular/devfile.yaml
Add new patched image (`che-nodejs10-community`) to replace `node:10.16-alpine` for the angular devfile (see discussion https://github.com/eclipse/che-devfile-registry/pull/38#issuecomment-513309951). I've tested the devfile on our dev-cluster deployment and there seem to be no issues (except `yarn install` failing once)
Use this [devfile](http://che-devfile-registry-eclipse-che.devtools-dev.ext.devshift.net/devfiles/angular/devfile.yaml)
Che 7.0.0 blocker: https://github.com/eclipse/che/issues/13454
> Update angular stack to use non-alpine image

- devfiles/apache-camel-springboot/devfile.yaml
che.openshift.io eclipse/che#13832
> Set back lower memory limits to have stack working by default on

- cico_release.sh
Fixing the release script to pass the correct version to the 'arbitrary-user-patch' image build
Related to https://github.com/eclipse/che/issues/13953 
Release CI - https://ci.centos.org/job/devtools-che-devfile-registry-release/
> che #13953 Fixing the release script to pass the correct version to the 'arbitrary-user-patch' image build

- devfiles/apache-camel-springboot/devfile.yaml
- cannot make it working even when attaching manually the Java debugger
afterwise
- Debug is available through CodeLens on the Application Java class
- no other devfiles are providing this kind of debug task
> Remove debug task in Camel stack eclipse/che#14003

- devfiles/java-mysql/devfile.yaml
- devfiles/java-mysql/meta.yaml
This PR fixes the Java MySQL devfile memory quotas in order to be able to run the devfile on OSIO
Issue: https://github.com/redhat-developer/che-functional-tests/issues/556
> Fixing Java MySQL sample devfile to be able to be run on OSIO

- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-spring/meta.yaml
This PR fixes the Java Springboot devfile memory quotas in order to be able to run the image on OSIO
Issue: https://github.com/redhat-developer/che-functional-tests/issues/556
> Fixed java-web-spring quotas to be able to run on OSIO

- devfiles/java-mysql/meta.yaml
- devfiles/java-web-spring/meta.yaml
Workaround for issue https://github.com/eclipse/che/issues/14096
Devfile `meta.yaml`s which specify `Gi` in their `globalMemoryLimit` display as `0Gi` in the stacks tab.
https://github.com/eclipse/che/issues/14096
> Update meta.yamls to use Mi instead of Gi

- devfiles/apache-camel-springboot/devfile.yaml
- devfiles/java-mysql/devfile.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-vertx/devfile.yaml
Sets up java-spring and java-vertx devfiles to support debugging.
- Adds a default debug config to each devfile so that clicking "Start debugging" works out of the box
- Modifies "run app" commands to start with debugging enabled
With these changes, the flow of "run webapp" -> "Start debugging" works without additional configuration.
https://github.com/redhat-developer/rh-che/issues/1434 (although this is not an osio-specific issue)
> Add debug configurations to java server devfiles

- devfiles/nodejs/devfile.yaml
Adds configuration to the node-express devfile to allow easier debugging setup:
- Adds task to launch with `--inspect` flag
- Adds debug config so that `F5` connects to running server.
redhat-developer/rh-che#1434 (Debugging working is in the acceptance criteria)
> Add debug configuration to node-express devfile

- devfiles/go/devfile.yaml
Improves the go devfile:
- Adds a default debug config that makes it easier to debug the current file.
- Adds "Stop outyet" task, since otherwise stopping the server either requires executing `kill` in a terminal or sending `ctrl+C` to the `run outyet` task's tab (which is entirely empty)
- Also stopping the running task is necessary to start debugging
https://github.com/redhat-developer/rh-che/issues/1434 (Debugging working is in the acceptance criteria)
> Add debug config and stop command for go devfile

- devfiles/go/devfile.yaml
- devfiles/java-gradle/devfile.yaml
- devfiles/java-maven/devfile.yaml
- devfiles/php-laravel/devfile.yaml
- devfiles/php-symfony/devfile.yaml
- devfiles/php-web-simple/devfile.yaml
Update devfiles so that exposed ports match those used by the sample app:
- golang: add port `8080`
- java-gradle: remove unused port (simple console app)
- java-maven: remove unused port (simple console app)
- php-laravel: update port to `8000` (instead of `8080`)
- php-symfony: update port to `8000` (instead of `8080`)
- php-web-simple: Add endpoint for port `8080`
https://github.com/redhat-developer/rh-che/issues/1434 (though not osio-specific)
> Make devfile endpoints match their sample apps

- devfiles/java-maven/devfile.yaml
Removing '-Duser.home=/home/user' workaround since '/home/user' exists and setup correctly
related to https://github.com/redhat-developer/rh-che/issues/1434
> removing '-Duser.home=/home/user' workaround since '/home/user' exists and setup correctly

- cico_build_ci.sh
- cico_functions.sh
Always tag images based on the git commit hash as part of every CI ('master', 'nightly', 'release')
N/A
> Always tag images based on the git commit hash as part of every CI ('master', 'nightly', 'release')

- devfiles/php-mysql/devfile.yaml
- devfiles/php-web-simple/devfile.yaml
Adds a command to simpler php devfiles to configure `DocumentRoot` and avoid showing an index page when the application is launched.
Without PR:
With PR (after configure task has been executed)
https://github.com/eclipse/che/issues/13964
> Add command to configure DocumentRoot in php devfiles

- devfiles/angular/devfile.yaml
- devfiles/apache-camel-springboot/devfile.yaml
- devfiles/dotnet/devfile.yaml
- devfiles/go/devfile.yaml
- devfiles/java-gradle/devfile.yaml
- devfiles/java-maven/devfile.yaml
- devfiles/java-mysql/devfile.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-vertx/devfile.yaml
- devfiles/nodejs-mongo/devfile.yaml
- devfiles/nodejs-react/devfile.yaml
- devfiles/nodejs/devfile.yaml
- devfiles/php-laravel/devfile.yaml
- devfiles/php-mysql/devfile.yaml
- devfiles/php-symfony/devfile.yaml
- devfiles/php-web-simple/devfile.yaml
- devfiles/python-django/devfile.yaml
- devfiles/python/devfile.yaml
Signed-off-by: Michal Vala <mvala@redhat.com>
updates devfiles to use `generateName` instead of just name.
Targeted to v7.1.0
https://github.com/eclipse/che/issues/13794
merge after this PR https://github.com/eclipse/che/pull/14157 !!!
> use generateName instead of just name

- Dockerfile
- Dockerfile.rhel
- check_mandatory_fields.sh
- index.sh
Replaces [`mikefarah/yq`](https://github.com/mikefarah/yq) with [`kislyuk/yq`](https://github.com/kislyuk/yq) and reworks `index.sh` and `check_mandatory_fields.sh` to accommodate this change.
- `index.sh` is greatly simplified and can basically be done in one step (with a workaround for self-links)
- `check_mandatory_fields.sh` no longer uses yq at all, since a simple grep command is sufficient to check if the fields are not present or empty.
Since timing is a concern in eclipse/che#14076, 
```
$ time ./check_mandatory_fields.sh devfiles
real	0m 0.05s
user	0m 0.03s
sys	0m 0.01s
$ time ./index.sh > /build/devfiles/index.json
real	0m 0.26s
user	0m 0.21s
sys	0m 0.04s
```
It's some minor work from testing https://github.com/eclipse/che/issues/14076
> Replace mikefarah/yq with kislyuk/yq

- devfiles/dotnet-asp.net/devfile.yaml
- devfiles/dotnet-asp.net/meta.yaml
Adds stack for developing ASP.NET Core web application
https://github.com/gothinkster/aspnetcore-realworld-example-app
> Add ASP.NET devfile

- devfiles/apache-camel-springboot/devfile.yaml
~requires https://github.com/eclipse/che-plugin-registry/pull/186~ --> Merged
> Change identifier of plugin used for Camel eclipse/che#13921

- arbitrary-users-patch/build_images.sh
Remove the `--squash` parameter from the CI build, as it fails on CentOS CI:
```
Building quay.io/eclipse/che-python-3.6:nightly based on centos/python-36-centos7:1 ...
"--squash" is only supported on a Docker daemon with experimental features enabled
Connection to 172.19.2.52 closed.
```
Nightly build failing: https://ci.centos.org/job/devtools-che-devfile-registry-nightly/539/console
> Remove --squash from docker build so CentOS CI can build it.

- arbitrary-users-patch/base_images
- devfiles/cpp/devfile.yaml
- devfiles/cpp/meta.yaml
It adds the devfile to work with c/c++ stack
https://github.com/eclipse/che/issues/13698
> Add the devfile to work with c/c++ stack

- cico_functions.sh
Fixing the release job - https://ci.centos.org/job/devtools-che-devfile-registry-release/13/
'arbitrary-users-patch' images should be built & pushed only as part of the 'centos' target execution.
Currently, the build is failing when pushing 'arbitrary-users-patch' to `quay.io/openshiftio/` which is smth that the release job should not do.  'arbitrary-users-patch' should be pushed only to the https://quay.io/organization/eclipse
Fixing the release job - https://ci.centos.org/job/devtools-che-devfile-registry-release/13/
> Fixing the release job. 'arbitrary-users-patch' images should be build & pushed only as part of the 'centos' target execution

- cico_functions.sh
Fixes an issue in the CI: since https://github.com/eclipse/che-devfile-registry/pull/105 disables building patched base images for RHEL-target release builds, we need to also not update the devfiles to point at the RHEL registry/organization. Otherwise, devfiles in the RHEL version of the repo will point at the `quay.io/openshiftio/<images>/<tag>` images that are no longer built.
Release CI
> Don't update registry and org in RHEL release builds

- devfiles/java-gradle/devfile.yaml
- devfiles/java-maven/devfile.yaml
We have two stacks with java11 images, but development tools used with [java8 version](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/latest/meta.yaml#L16). This pr fix it.
none
> Use java11 language tool for stacks with java11.

- arbitrary-users-patch/build_images.sh
- arbitrary-users-patch/happy-path/Dockerfile
- arbitrary-users-patch/happy-path/build_happy_path_image.sh
- cico_build_nightly.sh
- cico_build_release.sh
- cico_functions.sh
Signed-off-by: Radim Hopp <rhopp@redhat.com>
This adds dockerfile for image based on che-java11-maven. This image contains pre-downloaded mvn artifacts and is used for testing (until now, we were using image based on some really old version of the base image)
https://github.com/eclipse/che/issues/14737
> Added dockerfile with precashed mvn articats for usage in tests.

- devfiles/php-web-simple/devfile.yaml
Add debug config  "Launch currently open script" for php-web-simple.
How to test it:
1. Create and start workspace from devfile.
2. Open file index.php from web-simple-php project
3. Set breakpoint in 3 line.
4. Open debug panel. Should be selected configuration  "Launch currently open script"
5. Click run button.
none, done in the frame of the testing sidecar images.
> Add debug config for php-web-simple.

- cico_functions.sh
Updating image name based on the rhel image renaming in order to fix the release CI - https://ci.centos.org/job/devtools-che-devfile-registry-release/17/console
Dockerfile Renaming was introduced in https://github.com/eclipse/che-devfile-registry/pull/115
N/A
> Updating image name based on the rhel image renaming

- cico_functions.sh
che #14916 Release CI should  build an image based on the git commit hash (required for Hosted Che release cycle)
https://github.com/eclipse/che/issues/14916
> che #14916 Release CI should  build image based on the git commit hash (required for Hosted Che release cycle)

- cico_functions.sh
Release CI should build image based on the git commit hash (required for Hosted Che release cycle)
https://github.com/eclipse/che/issues/14916
Cherry-picking https://github.com/eclipse/che-devfile-registry/pull/122
> che #14916 Release CI should build image based on the git commit hash (required for Hosted Che release cycle)

- arbitrary-users-patch/base_images
- devfiles/go/devfile.yaml
- devfiles/go/meta.yaml
Remove `che-golang-1.10` from list of arbitrary UID patched images in favor of `che-golang-1.12`. This PR will stop nightly/release builds of that image and make new workspaces created using to go devfile use 1.12. We still need to decide what to do with the existing `che-golang-1.10` images on quay.io, since old workspaces may depend on it.
https://github.com/eclipse/che/issues/14265
> Deprecate che-golang-1.10 in favor of che-golang-1.12

- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.install.sh
- build/scripts/cache_projects.sh
Changes offline functionality so that cached project zips are instead `git clone`d and `git archive`d.
Fixes https://github.com/eclipse/che/issues/14800
> Improve how offline project zips are created

- build.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.Dockerfile
- build/scripts/list_referenced_images.sh
Adds building a list of externally-referenced images to the offline build to make it easier for users to know which images need to be pulled into a private registry.
Required for https://github.com/eclipse/che/issues/14866
Also rewrites the `build.sh` script to be similar to the one in the plugin registry (with options)
> Add list of external images to server when offline registry is built

- README.md
- build/dockerfiles/entrypoint.sh
Change environment variable for offline public endpoint to `CHE_DEVFILE_HTTP_ENDPOINT` instead of HTTPS since it is confusing.
> Update offline registry endpoint env var to not mention https

- build/dockerfiles/entrypoint.sh
Fixes the image regex we use to break an image reference into `repo/org/image:tag`. Currently it fails to match if registry hostname contains a port, since it does not match the colon.
https://github.com/eclipse/che/issues/14990
> Fix regex used for processing image references

- .github/CODEOWNERS
Add @ibuziuk as codeowner, to help with pushing through smaller changes that still require codeowner approval.
Mergability of simple PRs such as https://github.com/eclipse/che-devfile-registry/pull/134
> Add ibuziuk to codeowners

- deploy/openshift/che-devfile-registry.yaml
Adding cpu and memory requests / limits to the openshift template:
Usage from production:
ram: 13Mb
cpu: 0.002 
https://github.com/redhat-developer/rh-che/issues/1664
NOTE: must be also backported to 7.3.x branch https://github.com/eclipse/che-devfile-registry/pull/142
> Adding cpu and memory requests / limits to the openshift template

- arbitrary-users-patch/happy-path/build_happy_path_image.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/rhel.Dockerfile
- build/scripts/cache_images.sh
- build/scripts/cache_projects.sh
- build/scripts/check_mandatory_fields.sh
- build/scripts/index.sh
- build/scripts/list_containers.sh
Adds caching devfile icons to offline devfile registry builds.
A second commit also fixes any shellcheck errors across the repository.
https://github.com/eclipse/che/issues/15090
> Devfile icon caching for offline devfile registry

- arbitrary-users-patch/happy-path/build_happy_path_image.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/rhel.Dockerfile
- build/scripts/cache_images.sh
- build/scripts/cache_projects.sh
- build/scripts/check_mandatory_fields.sh
- build/scripts/index.sh
- build/scripts/list_containers.sh
- build/scripts/list_referenced_images.sh
- devfiles/java-mysql/devfile.yaml
- devfiles/nodejs-mongo/devfile.yaml
- devfiles/php-laravel/devfile.yaml
- devfiles/php-mysql/devfile.yaml
- devfiles/php-symfony/devfile.yaml
Cherry-pick fixes for 7.3.2
Pulls in changes from
- https://github.com/eclipse/che-devfile-registry/pull/136
- https://github.com/eclipse/che-devfile-registry/pull/140
https://github.com/eclipse/che/issues/15107
> Cherry-pick airgap fixes to 7.3.x

- arbitrary-users-patch/base_images
Patches quay.io/quarkus/centos-quarkus-maven:19.2.1 to use it Quarkus devfile as a dev environment.
**This image contains:**
OpenJDK 1.8.0_232
GraalVM 19.2.1
Apache Maven 3.6.1 
https://github.com/eclipse/che/issues/14506
> Prepare an image for Quarkus dev environment

- devfiles/apache-camel-k/devfile.yaml
- devfiles/apache-camel-k/meta.yaml
this is a first iteration with minimal set of plugins (Camel K,
Kubernetes, xml) and a pointer to Camel K official examples
To test:
can create workspace with https://<your-che-host>/f?url=https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml
- need to log to a Kubernetes cluster on which Camek K runtime is installed or can be installed, some potential ways:
-- chectl workspace:inject -k (if you're locally logged to on and Che is installed locally)
-- open terminal in the workspace, create ~/.kube/config with content retrieved from `kubectl config view --raw --flatten --minify` command launched in a place where you are logged in
- in case Camel K is not yet installed AND you have enough rights
-- switch to che namespace …
> feat(core): Provide an Apache Camel K stack eclipse/che#14831

- build/scripts/cache_images.sh
Fix bug reading list of images specified in meta.yamls, where more than one unique URL would cause caching script to fail.
https://github.com/eclipse/che/issues/15293
> Fix caching of images when multiple images specified

- devfiles/dotnet/devfile.yaml
Adds `preLaunchTask` into .Net debug configuration
https://github.com/eclipse/che/issues/15025
> Add preLaunchTask into .Net debug configuration

- build/scripts/cache_images.sh
Cherry pick changes from https://github.com/eclipse/che-devfile-registry/pull/150 in order to fix icon caching in the devfile registry.
https://github.com/eclipse/che/issues/15293
> Fix caching of images when multiple images specified (#150)

- deploy/kubernetes/che-devfile-registry/templates/configmap.yaml
Sets CHE_DEVFILE_REGISTRY_URL environment variable.
It will be replaced base URL to `http://{Pod's local IP}:8080/` if this environement variable wasn't set in `offline-registry` mode. 
I'm not an OpenShift specialist. So I just fixed for Kubernetes by this patch.
But I guess a similar patch will be required on OpenShift also.
None.
> Set CHE_DEVFILE_REGISTRY_URL environment variable.

- devfiles/java-mongo/devfile.yaml
Renames `centos/mongodb-34-centos7` to `docker.io/centos/mongodb-34-centos7`.
None.
> Normalize the image name.

- devfiles/che4z/devfile.yaml
- devfiles/che4z/meta.yaml
Added debugger-for-mainframe and hlasm-language-support
Signed-off-by: Filip Kroupa <filip.kroupa@broadcom.com>
Update Che4z devfile to include newly added plugins [eclipse/che-plugin-registry#322](https://github.com/eclipse/che-plugin-registry/pull/322)
Targetting [Milestone 7.6.0](https://github.com/eclipse/che/milestone/107)
N/A
> Che4z-1.1.0

- .github/workflows/main.yml
Add CI for pull requests that
1. Runs shellcheck on all scripts
2. Builds the registry
3. Builds an offline registry
To test, I added it to [my fork](https://github.com/amisevsk/che-devfile-registry/pull/1/checks)
Fixes https://github.com/eclipse/che/issues/14867
> Set up CI for repo using github actions

- devfiles/quarkus/devfile.yaml
- devfiles/quarkus/meta.yaml
Adds a devfile to support Qurakus tools.
- 2 components:
- dev component is based on `quay.io/quarkus/centos-quarkus-maven:19.2.1` which contains Java 8,  Maven 3.6.0 and GraalVM 19.2.1
- qurkus plugin (for more information take a look at https://github.com/eclipse/che-plugin-registry/pull/291)  
- 2 commands:
- mvn package
- mvn compile quarkus:dev
- The application could be debugged by predefined debug configuration in case `mvn compile quarkus:dev` was executed before.
This devfile doesn't include commands to run native compilation because it requires more than 3GB RAM for workspace in total and it's not available on Hosted Che.   
https://github.com/eclipse/che/issues/14506
> Add Quarkus devfile

- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.Dockerfile
In docker, copying from a previous stage does not preserve permissions when it creates a directory; this results in the /var/www/html/devfiles directory not having group write permissions, which in turn causes the airgap options to fail.
Fixes https://github.com/eclipse/che/issues/15547
> [airgap] Fix permissions on /var/www/html/devfiles

- devfiles/java-mongo/devfile.yaml
The mongodb container in the java-mongo devfile mounts a volume, which causes it to be unrunnable on Hosted Che. 
This PR adds a volume for the mongodb container to make it runnable, but there's no way to force a volume such as this to be emptyDir, so we do introduce all the risks of storing more data in a PV (slow writes, potentially, etc.).
Fixes https://github.com/eclipse/che/issues/15850
> Add docker image volume to mongo container in java-mongo devfile

- .github/CODEOWNERS
To start, owners are the one which are responsible of the repository.
Other committers will be able to merge as well when repository settings will be updated (as discussed in the Eclipse Che calls)
N/A
Change-Id: Ife8c69d1c6b9331986e808922f83663f3abcdd59
> chore(github): Update owners to match the team responsible of repo

- devfiles/cpp/devfile.yaml
- devfiles/dotnet-asp.net/devfile.yaml
This PR fixes terminal launching that was caused by overridden entrypoint that initializes /etc/passwd file.
https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L79
Actually, there is some bug in che-machine-terminal and missing /etc/passwd should not prevent the terminal from launching but it's another issue I'll try to handle in a scope of https://github.com/eclipse/che-machine-exec/pull/82
It fixes https://github.com/eclipse/che/issues/15969
> Do not override entrypoint that initializes /etc/passwd file

- arbitrary-users-patch/build_images.sh
- build.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/content_sets_centos8_appstream.repo
- build/dockerfiles/content_sets_epel7.repo
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/rhel.Dockerfile
- build/dockerfiles/rhel.entrypoint.sh
- build/dockerfiles/rhel.install.sh
- build/scripts/cache_images.sh
- build/scripts/cache_projects.sh
- build/scripts/index.sh
- build/scripts/write_image_digests.sh
- cico_build_ci.sh
- cico_build_nightly.sh
- cico_build_release.sh
- cico_functions.sh
- deploy/kubernetes/che-devfile-registry/Chart.yaml
- deploy/kubernetes/che-devfile-registry/templates/configmap.yaml
- deploy/kubernetes/che-devfile-registry/templates/deployment.yaml
- deploy/kubernetes/che-devfile-registry/templates/ingress.yaml
- deploy/kubernetes/che-devfile-registry/templates/service.yaml
- deploy/kubernetes/che-devfile-registry/values.yaml
- deploy/openshift/che-devfile-registry.yaml
Note: this PR is a port of https://github.com/eclipse/che-plugin-registry/pull/379
Add script /build/scripts/write_image_digests.sh, which will rewrite all image references in registry to use the current digest for each image tag. E.g.
```  
- type: dockerimage
alias: maven
image: "quay.io/eclipse/che-java11-maven:nightly"
```
is replaced with
```
- type: dockerimage
alias: maven
image: "quay.io/eclipse/che-java11-maven@sha256:1f8fb2175601f1b1cbb35a4250c817ada42dc6c388c710c696802cfba512f1ed" # tag: quay.io/eclipse/che-java11-maven:nightly
```
To enable this functionality, it is necessary to install `skopeo` in the builder images, which required changing adding the CentOS8-AppStream repo for the rhel build.
Digest-rewriting functionality is disabled by default and can be enabled by using …
> Add option to use digests for images referenced in registry

- devfiles/java-mysql/devfile.yaml
- devfiles/java-mysql/meta.yaml
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR increases the memory for java-mysql devfile so that it won't run into memory issues when running `maven build`. Tested locally and on che.openshift.io.
https://github.com/eclipse/che/issues/15911
> Increase memory for java-mysql petclinic devfile

- build/scripts/write_image_digests.sh
Don't overwrite image references with nonsense when we can't access the image being used.
Fixes https://github.com/eclipse/che/issues/16281
> Don't rewrite image digests for images we can't read

- arbitrary-users-patch/Dockerfile
- arbitrary-users-patch/base_images
- arbitrary-users-patch/entrypoint.sh
- devfiles/java-gradle/meta.yaml
Updates **che-java11-gradle** image to use Gradle v.6.2.1;
Patches `/etc/group` by adding arbitrary user
@amisevsk @nickboldt I added current arbitrary user into /etc/group because I got a message after opening the terminal:
` groups: cannot find name for group ID 1000160000`
Any concerns of that?
https://github.com/eclipse/che/issues/15723
> Update gradle image to use Gradle6; Add user to /etc/group

- build/scripts/cache_projects.sh
- devfiles/quarkus/devfile.yaml
Support the `sparseCheckoutDir` option when caching offline projects. Turns out it's not hard to do (though it took some time before I noticed the option in `git-archive`...)
Camel-k stack has additional commands present in Theia due to package.json files elsewhere in the repo.
> Support sparseCheckoutDir for offline cached projects

- devfiles/go/devfile.yaml
Use golang tool with non go modules to fix file imports intelligence, because we are using sample without go modules.
https://github.com/eclipse/che/issues/16427
> Use golang tool with non go modules mod to fix intelligence

- devfiles/go/devfile.yaml
Fixes issue where Che will complaing about the Go LS
not being up to date.
See eclipse/che#16113
> Set useLanguageServer preference to true

- arbitrary-users-patch/base_images
Update base image for PHP to that which is located in che-dockerfiles/che-php-base.
See eclipse/che#15854
> Update PHP base image

- build/scripts/write_image_digests.sh
CRW-653 support optional extra processing to check backup registries; tweak console output to report digest and source image if successful, and which image failed if skipping
Change-Id: Ic47c1349ad7172438e54839e04ee9e800e291037
> CRW-653 support optional extra processing to check backup registries

- arbitrary-users-patch/base_images
- devfiles/quarkus/meta.yaml
Use latest tag of centos-quarkus-maven: 20.0.0-java8
Needed to have native compilation working with the default Quarkus sample
> Use 20.0.0-java8 tag of centos-quarkus-maven

- devfiles/java-mongo/devfile.yaml
- devfiles/java-mysql/devfile.yaml
Applying memory limit fixes for mysql & mongo devfiles.
PR for master - https://github.com/eclipse/che-devfile-registry/pull/224 from @mingfang 
Applying memory limit fixes for mysql & mongo devfiles
https://github.com/eclipse/che/issues/16583
> che #16583 Applying memory limit fixes for mysql & mongo devfiles

- devfiles/java-mongo/devfile.yaml
- devfiles/java-mysql/devfile.yaml
Fix memoryLimit to Mi instead of Mib since the latest is not valid anymore
https://github.com/eclipse/che/issues/16572
> Fix memoryLimit to Mi instead of Mib since the latest is not valid anymore

- devfiles/dotnet/devfile.yaml
quick fix https://github.com/eclipse/che/issues/16748
original issue: https://github.com/eclipse/che/issues/16381
> Quick fix .net core stack endpoint name so it picks the right url in the preview pane

- devfiles/quarkus/devfile.yaml
Why:
* "Development server" is not the right term for quarkus:dev (since 1.4
there command mode which is not a server.
* All Quarkus apps and examples by default comes with mvn wrapper. That
should be the default used.
This change addreses the need by:
* Make 'development server' 'Development mode"
* Update tasks to use `./mvnw` instead of `mvn`
https://github.com/eclipse/che/issues/16701
> dev mode + ./mvnw for quarkus

- arbitrary-users-patch/base_images
Using 20.0.0-java11 instead of 20.0.0-java8 centos-quarkus-maven https://quay.io/repository/quarkus/centos-quarkus-maven?tag=20.0.0-java11&tab=tags
Partly solving https://github.com/eclipse/che/issues/16790
> Use the quarkus java11 image in our quarkus stack

- build/dockerfiles/fedora.repo
- build/dockerfiles/rhel.Dockerfile
- build/dockerfiles/rhel.install.sh
> S390x support

- devfiles/java-mongo/devfile.yaml
- devfiles/nodejs-mongo/devfile.yaml
This provides multi-arch support.
Fixes eclipse/che#16952
> Upgrade mongodb images to 3.6 from 3.4

- build/scripts/list_referenced_images.sh
Include referenced images from referenced kubernetes content to external_images.txt. Actual after merge: https://github.com/eclipse/che-devfile-registry/pull/147
https://github.com/eclipse/che/issues/16815
> Include referenced images from referenced kubernetes content to external_images.txt

- arbitrary-users-patch/base_images
Signed-off-by: Michal Vala <mvala@redhat.com>
Updates maven base image to latest v3.6.3. We need this to be able to build che-server in Che.
che-server dogfooding
> update maven to latest 3.6.3

- devfiles/quarkus/meta.yaml
Updating quarkus stack description
https://github.com/eclipse/che/issues/17311
> Updating quarkus stack description: Maven 3.6.3 and jdk11

- arbitrary-users-patch/base_images
This PR add a new docker image for golang version 1.14
> Add new image for golang 1.14

- devfiles/quarkus/devfile.yaml
The native image from quarkus is to build the native image not to run it. Similar to centos-quarkus-maven.
This is fixing it using ubi-minimal
> Update quarkus devfile: using ubi-minimal

- devfiles/java-web-spring/devfile.yaml
Uses `eclipse/che-java11-maven:nightly` image instead of `eclipse/che-java8-maven:nightly`
I checked code can be built and run with Java11 by hand.
None.
> [java-web-spring] Use che-java11-maven:nighty instead of Java8.

- devfiles/java-web-spring/devfile.yaml
bump java to java11 for tooling as well
Can be tested with http://che.openshift.io/f/?url=https://raw.githubusercontent.com/benoitf/che-devfile-registry/bump-java11/devfiles/java-web-spring/devfile.yaml
Change-Id: I50257b0d456c54a19985aa1735abcea47974572c
> feat(java11): Bump tooling to java11 as well

- build/scripts/cache_projects.sh
- devfiles/java-web-spring/devfile.yaml
For now it was using `master` branch by default even if commitId was set.
As some repositories are using `main` it was failing
Also sets commitId for java-web-spring to avoid to depends on 'latest' changes
Fixes https://github.com/eclipse/che/issues/17299
Alternate PR for https://github.com/eclipse/che-devfile-registry/pull/255
cc @monaka 
Change-Id: I91d5192209a1a5fbc29664eab9440722f28e97d7
> feat(offline): Handle commitId properly

- devfiles/java-web-spring/meta.yaml
Stacks was updated to use Java 11 and not java8, updating description
https://github.com/eclipse/che-devfile-registry/pull/257
> fix(version): 8-->11

- build/dockerfiles/Dockerfile
upstream tag image has been updated https://github.com/docker-library/httpd/commit/ea20f356a6f7d5b22793d0a51d82d6fccd08a6aa
it removes build dependencies but we were using bash transitively and it fails
add bash
good news: the image is A LOT smaller !
https://github.com/eclipse/che/issues/17345
Change-Id: I3f267521360ee0214bc0196561bd0c7ba164eacc
> fix(entrypoint): fix image error

- arbitrary-users-patch/base_images
New version of Quarkus currently supports GraalVM 19.3.2 and 20.1.0.
> update quarkus image to use GraalVM 20.1.0.

- devfiles/quarkus/devfile.yaml
> Switch to quarkus-java11 by default

- devfiles/go/devfile.yaml
Adds another one sample project to Go stack.
Adds commands to build and run sample project.
If the `golang/go` plugin could not be found when creating a workspace from the devfile, the `id` should be replaced on `reference`.
```
-
type: chePlugin
reference: >-
https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/golang/go/0.14.4/meta.yaml
alias: go-plugin
memoryLimit: 512Mi
env:
- value: 'off'
name: GO111MODULE
preferences:
go.lintTool: 'golangci-lint'
go.lintFlags: '--fast'
go.useLanguageServer: true
```
Solves issue https://github.com/eclipse/che/issues/13803
> Add sample project to Go stack

- .ci/devfile-images-check.sh
- .github/workflows/main.yml
Signed-off-by: flacatus <flacatus@redhat.com>
This PR create a new ci script which basically check all new container images created/changed in the `devfile.yaml` files. This CI scripts will run using github actions. The job name is `digest-validation`.
I tested this job in one of my repo: https://github.com/flacatus/github-actions/pull/4
Reference issue: https://github.com/eclipse/che/issues/17368
> Check container images digest in PRs

- devfiles/che4z/devfile.yaml
Remove bitlang cobol plugin from Mainframe Basic Stack
MERGE NOTE: Due to plugin dependencies, please merge this PR together with [https://github.com/eclipse/che-plugin-registry/pull/598](https://github.com/eclipse/che-plugin-registry/pull/598)
> Remove bitlang cobol from Che4z

- devfiles/cpp/devfile.yaml
Uses `eclipse-cdt/cdt-vscode/latest` instead of `che-incubator/cpptools/latest`.  It is deprecated.
None.
> Use latest CDT plugin.

- arbitrary-users-patch/base_images
- devfiles/nodejs-yarn/devfile.yaml
Adds more memory for dev container;
Change the command to install dependencies from `yarn install` to `npm instaal`. Looks like yarn cannot install dependencies because the .node_modules was marked as symlink.
https://github.com/eclipse/che/issues/17453
> Update the command of installing dependencies in NodeJS+Yarn devfile

- devfiles/go/devfile.yaml
Removes `cheEditor` from components.
It is redundant because Che will choose its default editor from `CHE_FACTORY_DEFAULT__EDITOR` variable.
None.
> [Golang] Remove cheEditor from components.

- arbitrary-users-patch/base_images
Signed-off-by: Esteban Mañaricua <emanaricua@gmail.com>
when testing example kotlin apps I am using the gradle+jdk11 cli image and I get:
````Gradle
buildscript {
ext.kotlin_version = '+'
ext.autoparcel_version = '1.0.1'
repositories {
jcenter()
google()
}
dependencies {
classpath 'com.android.tools.build:gradle:+'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}
}
````
produces:
````verilog
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
> Minimum supported Gradle version is 6.6.1. Current version is 6.2.1. If using the gradle wrapper, try editing the distributionUrl in /projects/kotlin/gradle/android-auto-parcel/gradle/wrapper/gradle-wrapper.properties to gradle-6.6.1-all.zip
```` …
> Bump gradle to 6.6.1

- devfiles/quarkus/meta.yaml
This is how the Quarkus stack appears in the getting started today:
But this is not a "Quarkus Tools" stack. This is a "Quarkus" stack. Hence removing the word "Tools".
> Remove "Tools" from the Quarkus stack name

- arbitrary-users-patch/base_images
Adds a base image for python devfiles using python 3.8.6
https://github.com/eclipse/che/issues/16183
> Add python 3.8 base image

- .github/PULL_REQUEST_TEMPLATE.md
Add the new PR Template
https://github.com/eclipse/che/issues/17486
Change-Id: I632d9498d6c13808a21478424e01ca6244018fbe
> chore(github): Update the template to match new definition of done on PR

- arbitrary-users-patch/base_images
Fixed typo in base image name.
> Fix typo in python:3.8.6-slim base image name

- .github/workflows/build-jobs.yml
- .github/workflows/pr-checks.yml
- .github/workflows/pr-jobs.yml
Run a GitHub action job everytime a change is merged, instead of using centos-ci.
See eclipse/che#18072
> Switch nightly build to GH action

- arbitrary-users-patch/base_images
Add new UID-patched image for Antora. 
Antora is used for building Che docs, but the [devfile](https://github.com/eclipse/che-docs/blob/3e9b404c0bef89b86546555213ffe0ee1c646799/devfile.yaml#L9) uses the default docker.io repo image, which could encounter UID issues as we've seen in the past.
If this PR is approved, a repo in quay.io/eclipse must be created for the new image before this PR is merged.
> Add antora to list of UID patch images

- devfiles/apache-camel-springboot/devfile.yaml
- devfiles/java-gradle/devfile.yaml
- devfiles/java-maven/devfile.yaml
- devfiles/java-mongo/devfile.yaml
- devfiles/java-mysql/devfile.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-vertx/devfile.yaml
This PR points some of the devfiles which uses Java 8 to use redhat/java8 plugin, since redhat/java plugin was migrated to Java 11 in https://github.com/eclipse/che-plugin-registry/pull/654 
Adds` java.server.launchMode:Standard` preference for redhat/java11 plugin to not have the vscode-java prompt
https://github.com/eclipse/che/issues/18170
To test this changes you can create a workspace on che.openshift.io by using the content of changed devfile.
> Use java8 plugin instead of java

- devfiles/apache-camel-springboot/devfile.yaml
- devfiles/java-gradle/devfile.yaml
- devfiles/java-maven/devfile.yaml
- devfiles/java-mongo/devfile.yaml
- devfiles/java-mysql/devfile.yaml
- devfiles/java-web-spring/devfile.yaml
- devfiles/java-web-vertx/devfile.yaml
- devfiles/quarkus-command-mode/devfile.yaml
- devfiles/quarkus/devfile.yaml
- devfiles/scala-sbt/devfile.yaml
- Adds Java debug port to java container endpoints
- Marks debug port as private to prevent appearing extra notifications when running debug server
https://github.com/eclipse/che/issues/18138
To test changes your Che-Theia must have ports plugin from this PR https://github.com/eclipse/che-theia/pull/875
A devfile to test how it works with Quarkus stack
```
---
apiVersion: 1.0.0
metadata:
generateName: quarkus-command-mode-
projects:
-
name: quarkus-quickstarts
source:
type: git
location: "https://github.com/quarkusio/quarkus-quickstarts.git"
sparseCheckoutDir: getting-started-command-mode
components:
- type: cheEditor
reference: >-
https://gist.githubusercontent.com/vitaliy-guliy/f51fc177a6bdac3b7ba1c248b466d515/raw/f77b22e383bd9a978328e1912 …
```
> Make java debug port private for all Java devfiles

- devfiles/nodejs-mongo/devfile.yaml
- devfiles/nodejs/devfile.yaml
A [new version](https://github.com/eclipse/che-plugin-registry/pull/666) of `ms-vscode/node-debug` plugin requires `debug.node.useV3` workspace property set to `false`. Without this property, the debugger cannot connect to the node process.
It's better to merge this PR before merging the corresponding [PR to che-plugin-registry](https://github.com/eclipse/che-plugin-registry/pull/666), but it's not critical. 
Follow `How to test` section in the PR to plugin registry https://github.com/eclipse/che-plugin-registry/pull/666
> Add debug.node.useV3 workspace property

- cico_functions.sh
Authenticate to docker.io to prevent failing the build on Centos CI due to pull limits
* https://github.com/eclipse/che/issues/18292
* https://github.com/eclipse/che/issues/18409
> Add docker io login step to avoid pull limit issues on Centos CI

- devfiles/go/meta.yaml
Fixup for go devfile metadata: Dashboard lists the go stack as containing "Go 1.12.10" but version in actual container is `go version go1.14.9 linux/amd64`
> Fix version in go devfile metadata.

- devfiles/quarkus-command-mode/devfile.yaml
- devfiles/quarkus/devfile.yaml
It avoid the compilation to fail if it is reaching the memoryLimit defined for the container.
https://github.com/eclipse/che/issues/17138
- Command mode: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus-command-mode/devfile.yaml
- Rest API: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus/devfile.yaml
> fix(quarkus-devfiles): Limit the quarkus native compilation memory limits so it doesn't fail when it reaches the container limit

- devfiles/rust/devfile.yaml
Adding the Rust plugin to the rust devfile
Tested with
```yaml
- type: chePlugin
reference: 'https://gist.github.com/sunix/eb86fdf6802afbfb4de059ed19f08d37/raw/83db1b01e210c19209913fa37399846d9fd5fcbd/meta.yaml'
```
https://github.com/eclipse/che/issues/17069
- Create a workspace from the rust get started sample
- add the plugin above in the workspace devfile
- open main.rs, try code completion and error
> feat(rust-devfile): Adding the Rust plugin to the Rust stack

- .github/workflows/nightly-build-publish.yml
- .github/workflows/release-build-publish.yml
- .github/workflows/release.yml
Adds a GitHub action based release job system to the devfile registry.
N/A
Part of eclipse/che#18072
Modify the VERSION file on the `release` branch and push the changes.
> Add a GitHub action based release job

- devfiles/quarkus/devfile.yaml
Set `0.0.0.0` as a host to run Quarkus app
https://github.com/eclipse/che/issues/18512
Use this factory: https://che.openshift.io/factory?url=https://raw.githubusercontent.com/svor/che-devfile-registry/sv/quarkusFix/devfiles/quarkus/devfile.yaml
> Set 0.0.0.0 as a host to run Quarkus app

- .github/workflows/nightly-build-publish.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
Enables docker buildx support in GitHub Actions job to build and publish multiarch docker images. All the workflows (nightly build, PR check, and release) are updated to have multiarch support. 
This refers to [#17124](https://github.com/eclipse/che/issues/17124). As per @nickboldt's [comment](https://github.com/eclipse/che-devfile-registry/pull/250#issuecomment-740180491) on #250, raised this PR to add multiarch support.
> Multiarch build support by docker buildx

- README.md
- build.sh
Not all users have access to docker, so use podman/buildah by default and use docker as a last resort.
Fixes of eclipse/che#18798
Run the build script with `BUILDER=buildah ./build.sh`, or try running just `build.sh` and observe that a tool will be auto-detected based on what's installed on your machine.
> Add support for building with buildah

- devfiles/apache-camel-springboot/devfile.yaml
eclipse/che#18939
-adjusting for Camel on SpringBoot because we are close to max capacity
for the devfile
- no need to adjust for Camel K stack, picking the default is enough
eclipse/che#18939
Start Camel on SpringBoot stack
Open the CamelRouter.java file
check completion for Camel URI available
check Java completion is working (after awaiting the download of all dependencies which is taking several minutes)
> With latest VS Code language Support for Camel, minimal memory is 350Mi

- devfiles/bash/devfile.yaml
Change the bash sample to use `generateName`, matching other sample devfiles in this repo.
> Use generateName for bash devfile to match others

- deploy/kubernetes/che-devfile-registry/templates/configmap.yaml
- deploy/kubernetes/che-devfile-registry/templates/deployment.yaml
- deploy/kubernetes/che-devfile-registry/templates/ingress.yaml
- deploy/kubernetes/che-devfile-registry/templates/service.yaml
- deploy/openshift/che-devfile-registry.yaml
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
- Add default kubernetes labels
- Specify container limits
- Add securityContext:
```
securityContext:
capabilities:
drop:
- ALL
```
https://github.com/eclipse/che/issues/18357
> Add default kubernetes labels

- devfiles/quarkus/devfile.yaml
Currently `CHE_DEVFILE_REGISTRY_URL` reference is failing on production. 
workaround since we do not plan to update devfile registry on stg and production anymore
> Removing the CHE_DEVFILE_REGISTRY_URL from the plugin reference

- .github/workflows/nightly-build-publish.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- PLATFORMS
- arbitrary-users-patch/PLATFORMS
- arbitrary-users-patch/build_images.sh
- arbitrary-users-patch/happy-path/PLATFORMS
- arbitrary-users-patch/happy-path/build_happy_path_image.sh
- make-release.sh
Signed-off-by: Bivas Das <bivasda1@in.ibm.com>
Enables docker buildx support in GitHub Actions job to build and publish multiarch docker images. All the workflows (nightly build, PR check, and release) are updated to have multiarch support.
This refers to https://github.com/eclipse/che-devfile-registry/pull/321
@ericwill Could you please review this PR
> Added multiarch support by docker buildx

- devfiles/quarkus-command-mode/devfile.yaml
- devfiles/quarkus/devfile.yaml
Quarkus quickstart repos has its default branch renamed from `master` to `main`. It looks like it is an issue with sparseCheckoutDir. This is a quick-fix.
N/A
quick-fix for https://github.com/eclipse/che/issues/19346
Set your default devfile registry to https://sunix-che-devfile-registry-fix-quarkus-wuh9w.surge.sh, for instance:
```
kubectl edit CheCluster/eclipse-che -n eclipse-che
```
and use these values:
```
devfileRegistryUrl: https://sunix-che-devfile-registry-fix-quarkus-wuh9w.surge.sh
externalDevfileRegistry: true
```
Wait for che-server to be redeployed and verify that the Create a custom workspace from `Quarkus Rest API` template. Verify that `branch: main` is set. Start the workspace, verify that the project is cloned.
[As the author of this Pull Request I made sure …
> fix(quarkus-devfile): clone with sparseCheckoutDir not working after repository default branch change to main

- devfiles/go/devfile.yaml
- devfiles/quarkus/didact.md
Fix all devfiles after turning on multiroot
N/A
https://github.com/eclipse/che/issues/19375
With che nightly set the devfile registry to https://sunix-che-devfile-registry-multiroot-vjnfq.surge.sh/devfiles/
and try go-lang stack and quarkus stack
> fix(multiroot): fix devfiles so it works with default multiroot

- arbitrary-users-patch/PLATFORMS
- arbitrary-users-patch/build_images.sh
- arbitrary-users-patch/happy-path/PLATFORMS
- arbitrary-users-patch/happy-path/build_happy_path_image.sh
Partial revert of #336
Related to eclipse/che#19486
Run the release job and ensure dev containers were built.
> Disable multi-arch builds for dev containers and happy path

- .github/workflows/nightly-build-publish.yml
- arbitrary-users-patch/build_images.sh
- arbitrary-users-patch/happy-path/build_happy_path_image.sh
- make-release.sh
use --rm flag to purge images from local docker registry after they're pushed to remote
Change-Id: Ibf077cba35048b3bc72b7d4025eef5ffbd0f191c
N/A
last week we ran out of disk building the che-devfile-registry's stack/sidecar images. This seeks to improve that problem by deleting images from the local registry after we've pushed them to quay.
If building locally is a common usecase (outside of GH actions) we might want to refactor things a bit so that the `--rm` flag is an optional one passed to make-release.sh, rather than being a default setting when make-release.sh calls into the `arbitrary-users-patch` scripts. 
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-te …
> feature(disk cleanup) use --rm flag to purge images from local docker registry after pushing to remote

- build/dev/build-devfile-registry.sh
- build/dev/publish-devfile-registry-to-surge.sh
- build/dev/start-devfile-registry.sh
Signed-off-by: Sun Tan <sutan@redhat.com>
Allow other devfile registries git repo to reuse the same dogfooding scripts to build and publish.
For instance CRW or this one https://github.com/sunix/devfiles
An example of dashboard using multiple devfile registries built with these scripts:
Not related, but used this to mockup https://github.com/eclipse/che/issues/18473
Part of https://github.com/eclipse/che/issues/19305
Could be tested with the default dogfooding devfile: make sure build works
Could also be tested with https://github.com/sunix/devfiles/blob/master/devfile.yaml but changing the upstream repo with this branch
I tested days ago with CRW but did not push the devfile :(
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.m …
> chore(dog-fooding-extend): allow other repos that contain only devfiles folder to reuse the che-plugin-registry dogfooding scripts

- .github/workflows/sidecar-check.yml
- arbitrary-users-patch/check_sidecar_image_digests.sh
Add regularly scheduled workflow for checking sidecar image digests in base_images file. If new digest is detected, a pull request with it's update will be generated
> Add workflow for checking sidecar digests

- arbitrary-users-patch/build_images.sh
This PR adds support for an external `base_images` file in script `build_images.sh`.  My organization is creating custom dev containers (`dockerimage` components in devfiles) and I would like to benefit from the `entrypoint.sh` and modifications done by `arbitrary-users-patch/Dockerfile`.  But because the `base_image` file is hardcoded in the script, I cannot inject my own.  This PR adds a variable to do this.  The code is backward compatible, so no change is needed on your side.
N/A
N/A
> Adding support to provide external base_images file

- .github/workflows/sidecar-check.yml
to allow fetching digests from reg.access.redhat.com or reg.rh.io, log in using CRW_BUILD user and token (secrets already uploaded)
Change-Id: I39a770d52ab5f5a6f59611fc2c353c21a99ff057
N/A
Last run of  https://github.com/eclipse-che/che-devfile-registry/actions/workflows/sidecar-check.yml
created bad PR: https://github.com/eclipse-che/che-devfile-registry/pull/406/files
N/A
> chore: bug: to allow fetching digests from reg.access.redhat.com or reg.rh.io, log in using CRW_BUILD user and token (secrets already uploaded)

- build/dockerfiles/entrypoint.sh
Appends plugin registry root to `icon` and `self` links.
https://github.com/eclipse/che/issues/19140
1. build the devfile registry and upload the image to quay.io
```
./build.sh
docker tag quay.io/eclipse/che-devfile-registry:next quay.io/vgulyy/che-devfile-registry:test-links
docker push quay.io/vgulyy/che-devfile-registry:test-links
``` 
2. deploy Che using `patch.yaml`
```
chectl server:deploy --installer=operator --platform=crc --che-operator-cr-patch-yaml=patch.yaml
```
`patch.yaml` content
```
spec:
k8s: 
singleHostExposureType: 'gateway'
server:
serverExposureStrategy: single-host
devfileRegistryImage: quay.io/vgulyy/che-devfile-registry:test-links
```
To deploy I used `crc` instead of `minikube`, as it described in the issue.
But it …
> fix(links): Add plugin registry root at the beginning of `icon` and `self` links

- .ci/generate_and_publish_registry_url_devfiles.sh
Checks to see if any changes have been made before publishing to GitHub pages.
N/A
Failing publish job, i.e. https://github.com/eclipse-che/che-devfile-registry/runs/2895644565?check_suite_focus=true
Try locally to publish without making any changes -- it should fail.
> fix(gh-pages): publish only if devfiles have changed

- build/dockerfiles/entrypoint.sh
Do not need to replace links of images and self in devfile registry  if `CHE_DEVFILE_REGISTRY_URL` environment variable wasn't set into che-devfile-registry pod. 
https://github.com/eclipse/che/issues/20100
1. Build the devfile registry and upload the image to quay.io
2. Set your image into [che-devfile-registry custom chart](https://github.com/eclipse-che/che-server/blob/main/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml#L15)
3. Deploy che via 
```
cd <CHE_SERVER_REPOSITORY>/deploy/kubernetes/helm/che
helm dependency update
chectl server:deploy --platform minikube --installer helm -m --templates <CHE_SERVER_REPOSITORY>/deploy/
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-templ …
> fix:don't replace URLs of devfile and images if CHE_DEVFILE_REGISTRY_URL env wasn't set

- devfiles/java-mysql/devfile.yaml
Fixes running of java-spring-petclinic project https://github.com/che-samples/java-spring-petclinic
https://github.com/eclipse/che/issues/19989
- Create a workspace from the [devfile](https://github.com/eclipse-che/che-devfile-registry/blob/b0501ca972290274f502e336b9e9874c04b385b6/devfiles/java-mysql/devfile.yaml)
> fix: update java mysql devfile

- build/dockerfiles/rhel.Dockerfile
This will deny access to security sensitive .ht files and increase the default encryption level for SSL.
https://issues.redhat.com/browse/CRW-2118
We use these settings downstream in IBM Wazi Developer for Workspaces.
> fix: CRW-2118: Contributing security updates for httpd

- devfiles/java-web-spring/devfile.yaml
Increases the value of memoryLimit for dev container to fix build command.
N/A
1. Create a workspace from Java Spring Boot devfile
2. Run `maven build` command
> fix: increase memoryLimit in java-web devfile

- happy-path/Dockerfile
- Bumps happy path base image to quay.io/eclipse/che-java11-maven:ce0526f
- Solves an error https://github.com/eclipse-che/che-devfile-registry/runs/3950149195?check_suite_focus=true
To not block the release, tag `ce0526f` is set by hands.
Script to bump to the new tag after building and pushing of `quay.io/eclipse/che-java11-maven` will be provided in the next pull request.
https://github.com/eclipse/che/issues/20667
Run release script locally.
> chore(happy-path): bump happy path image to quay.io/eclipse/che-java11-maven:ce0526f

- make-release.sh
It's not clear why the build script fails https://github.com/eclipse-che/che-devfile-registry/runs/3951923478?check_suite_focus=true#step:10:45542
This fixup will run checking of necessary docker images sequentially. This hopefully will help to catch the error.
Path of https://github.com/eclipse/che/issues/19695
Run the make-release script locally.
> chore(make release): check the images existence sequentially (not in parallel)

- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.Dockerfile
- build/scripts/generate_devworkspace_templates.sh
- build/scripts/index.sh
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Generate DW templates at build time and put them into `/usr/local/apache2/htdocs/devfiles/v2/che-thei/` folder in the che-devfile-registry image.
fixes https://github.com/eclipse/che/issues/19718
1. Build and run the `che-devfile-registry` image.
2. Go to `<devfile-registry URL>/devfiles/v2/che-theia/`.
3. See: List of the generated tamplates.
> chore: Pre-build DevWorkspace templates for devfile v2

- build/dockerfiles/entrypoint.sh
Makes deWorkspace links absolute
Values of `eclipse/che-theia/latest` and `eclipse/che-theia/next` should be published as absolute link. For now they are published with relative link: https://eclipse-che.github.io/che-devfile-registry/main/devfiles/
- Run the built image
- set env: `export CHE_DEVFILE_REGISTRY_URL=https://eclipse-che/main`
- run entrypoint.sh in `/usr/bin` directory
- check the content of `/var/www/html/devfiles/index.json`
> chore: add public url prefix for deWorkspaces links

- build/dockerfiles/Dockerfile
- build/dockerfiles/entrypoint.sh
- build/scripts/cache_projects.sh
- build/scripts/clone_and_zip.sh
- build/scripts/generate_devworkspace_templates.sh
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
* Clone and zip every git repository which is mentioned in the `v2` link
* Update the devfile v2 template with the link to the project zip
https://github.com/eclipse/che/issues/20720
1. Run `./build.sh` to build an image.
2. Run the image: `docker run -it --rm -p 8080:8080 quay.io/eclipse/che-devfile-registry:next`.
3. Check that `/resources/v2` folder is present and contains zip projects.
4. Check any `devworkspace-che-theia-next.yaml` or `devworkspace-che-theia-latest.yaml` to contain a project section with the zip in its location.
Reviewers, please comment how you tested the PR when …
> chore: Export git repositories as zip files for Devfile v2

- .ci/generate_and_publish_registry_url_devfiles.sh
- build/dev/publish-devfile-registry-to-surge.sh
- build/dev/start-devfile-registry.sh
- build/dockerfiles/entrypoint.sh
- build/scripts/generate_devworkspace_templates.sh
It avoids proxy/TLS/untrusted issue
related to https://github.com/eclipse/che/issues/20709
https://github.com/eclipse/che/issues/20709
(make sure your che operator is the nightly one including this fix: https://github.com/eclipse-che/che-operator/pull/1237)
Then open devfile registry with a browser to something like
`https://che-url/devfile-registry/devfiles/go/devworkspace-che-theia-latest.yaml`
see that the zip location is using `http://devfile-registry.eclipse-che.svc:8080/resources/v2/golang-echo-example.zip`
You can go inside for example dashboard container and do:
```
$ wget http://devfile-registry.eclipse-che.svc:8080/resources/v2/golang-echo-example.zip
```
file is downloaded as expected
[As the author of this Pull Request I made sure …
> feat: Update zip location for prebuilt samples with internal URL

- devfiles/apache-camel-k/meta.yaml
Add camel-k examples
There is an issue for Apache Camel Language Server but it's not related to the devfile itself
Issue found:
https://github.com/camel-tooling/camel-lsp-client-vscode/issues/836
PR to fix:
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/837
part of https://github.com/eclipse/che/issues/19341
Click on `https://che-server#https://github.com/che-samples/apache-camel-k/tree/devfilev2`
Go to the View/Output and check Apache Camel-k output
you should see that camel-k binary has been found on the filesystem.
Change-Id: …
> feat: introduce devfile v2 for Apache Camel-k

- build/scripts/generate_devworkspace_templates.sh
- build/scripts/index.sh
Add prebuilt templates for che-code
https://github.com/eclipse/che/issues/19906
Build and run devfile-registry
check http://localhost:8080/devfiles/ (and see new `devWorkspaces` links)
Also check http://localhost:8080/devfiles/quarkus/devworkspace-che-code-insiders.yaml
Change-Id: I200f609b1890c39dd63a335b00f160ae1b49fb9c
> feat: introduce che-code prebuilt templates

- build/dockerfiles/entrypoint.sh
Fix INTERNAL_URL not being updated for che-code templates
https://github.com/eclipse/che/issues/19906
Build the image, run the container with something like
```
$ docker run --rm -it -e CHE_DEVFILE_REGISTRY_URL=http://foo.bar -e CHE_DEVFILE_REGISTRY_INTERNAL_URL=http://another.baz -p 8080:8080 quay.io/eclipse/che-devfile-registry:next
```
And see that the INTERNAL_URL of the zip inside checode template has been updated
> fix: update all devWorkspace templates

- .github/CODEOWNERS
Removes tsmaeder from codeowners
> chore: remove tsmaeder from codeowners

- build/dockerfiles/Dockerfile
- build/scripts/list_referenced_images.sh
Get used images from devworkspace-templates*.yaml files
https://github.com/eclipse/che/issues/21574
build devfile registry and check **/usr/local/apache2/htdocs/devfiles/external_images.txt** file, it should contain the list of images
> fix: add list of used images into external_images.txt

- build/dockerfiles/Dockerfile
Apache HTTP Server restricts the size of the HTTP request header allowed from the client. Default value is set to 8192 (8 KB). In order to avoid request blocking by this limitation, httpd.conf has been adjusted to set 32768 (32 KB).
The size of the HTTP request header allowed from the client is limited to 32 KB (not to 8 KB by default) after this change.
You can sum cookie size on screenshot below - about 16 KB. And we got success response. 
https://github.com/eclipse/che/issues/21916
1. Deploy Che with `docker.io/karatkep/che-devfile-registry:hs-32kb` as devfile-registry image.
2. Call any devfile-registry URL, for example: GET /devfiles/index.json. Please see screenshot above.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.m …
> Increase the size of the HTTP request header allowed from the client to 32 KB

- build/dockerfiles/entrypoint.sh
- build/scripts/generate_devworkspace_templates.sh
- build/scripts/index.sh
Generates Dev Workspaces for all samples with `che-code/latest` editor and include them into the final image
https://issues.redhat.com/browse/CRW-3568
- Build  devfile-registry image and run it
- Go into `/usr/local/apache2/htdocs/devfiles`
- Check sample's folder
- `devworkspace-che-code-latest.yaml` should be there
- Check `/usr/local/apache2/htdocs/devfiles/index.json`
- It should contain links to dev workspaces with `che-incubator/che-code/latest` editor
> chore: generate DWs with che-code/latest

- tools/devworkspace-generator/src/devfile/dev-container-component-finder.ts
- tools/devworkspace-generator/src/generate.ts
- tools/devworkspace-generator/tests/devfile/dev-container-component-finder.spec.ts
- tools/devworkspace-generator/tests/generate.spec.ts
Ignore default components check when a devfile references a parent.
It needs for https://github.com/eclipse/che/issues/22103
1. Create a new workspace from https://gist.githubusercontent.com/olexii4/fc3b757806e660dee0fbe1bc131df3d1/raw/1212b86a69440a30d3d06cbe412c72bbbb665daf/empty.yaml
```
schemaVersion: 2.2.0
metadata:
generateName: empty
parent:
id: udi
registryUrl: https://registry.stage.devfile.io/
version: 1.0.0
```
> Ignore default components check when a devfile references a parent

- tools/devworkspace-generator/README.md
- tools/devworkspace-generator/src/devfile/dev-container-component-finder.ts
- tools/devworkspace-generator/src/devfile/dev-container-component-inserter.ts
- tools/devworkspace-generator/src/devfile/devfile-module.ts
- tools/devworkspace-generator/src/generate.ts
- tools/devworkspace-generator/src/main.ts
- tools/devworkspace-generator/tests/devfile/dev-container-component-finder.spec.ts
- tools/devworkspace-generator/tests/devfile/dev-container-component-inserter.spec.ts
- tools/devworkspace-generator/tests/generate.spec.ts
- tools/devworkspace-generator/tests/main.spec.ts
This PR provides an ability to inject a default dev container component into the DevWorkspace. For this, two additional parameters were added:
`--injectDefaultComponent:` inject a default dev container component if no component is defined in the devfile and it doesn't provide a parent, the value can be **true** or **false,** default is **false**
`--defaultComponentImage:` image to use for the dev container component that will be injected if injectDefaultComponent is true, default is **quay.io/devfile/universal-developer-image:ubi8-latest**
<details>
<summary>The resulted DevWorkspace</summary>
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
name: che-code-empty
spec:
commands:
- id: init-container-command
apply:
component: che-code-injector
- id: …
```
> chore:add default dev container component

- tools/devworkspace-generator/src/generate.ts
- tools/devworkspace-generator/tests/generate.spec.ts
Overrides a default `routingClass` by setting `routingClass: che` in a generated DevWorkspace:
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
name: spring-petclinic
spec:
started: true
routingClass: che
```
<details>
<summary>An example of the generated DevWorkspace</summary>
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
name: che-code-inventory-quarkus
spec:
commands:
- id: init-container-command
apply:
component: che-code-injector
- id: init-che-code-command
exec:
component: che-code-runtime-description
commandLine: >-
nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
2>&1 &
events:
preStart:
- init-container-command
postStart:
- init-che-code-command
components:
- name: …
```
> chore: add routingClass:che into generated DevWorkspace

- README.md
Updates Readme.md to fix instructions for running registry locally
> fix: update readme how to run locally

- tools/devworkspace-generator/src/generate.ts
- tools/devworkspace-generator/tests/generate.spec.ts
Update the generator to avoid adding **controller.devfile.io/merge-contribution** attribute into the developer container, it will be done by the DWO
N/A
https://github.com/eclipse/che/issues/22155
1/ Go to che-devfile-registry/tools/devworkspace-generator
2/ Build the tool by running yarn
3/ Generate a devworkspace:
```
node lib/entrypoint.js \
--devfile-url:https://github.com/che-samples/java-spring-petclinic/tree/main \
--plugin-registry-url:https://che-plugin-registry-main.surge.sh/v3/ \
--editor-entry:che-incubator/che-code/latest \
--output-file:/tmp/devworkspace-che-code-latest.yaml 
```
4/ Take a look at the generated file /tmp/devworkspace-che-code-latest.yaml, it should not contain **controller.devfile.io/merge-contribution** attribute in the components.
5/ Try to start a …
> feat: don't add merge-contribution attribute into the dev container

- build/scripts/generate_devworkspace_templates.sh
- build/scripts/update_devworkspace_templates.sh
- tools/devworkspace-generator/src/bitbucket-server/bitbucket-server-module.ts
- tools/devworkspace-generator/src/bitbucket-server/bitbucket-server-resolver.ts
- tools/devworkspace-generator/src/bitbucket-server/bitbucket-server-url.ts
- tools/devworkspace-generator/src/bitbucket/bitbucket-module.ts
- tools/devworkspace-generator/src/bitbucket/bitbucket-resolver.ts
- tools/devworkspace-generator/src/bitbucket/bitbucket-url.ts
- tools/devworkspace-generator/src/github/github-url.ts
- tools/devworkspace-generator/src/inversify/inversify-binding.ts
- tools/devworkspace-generator/src/main.ts
- tools/devworkspace-generator/src/resolve/git-url-resolver.ts
- tools/devworkspace-generator/src/resolve/resolve-module.ts
- tools/devworkspace-generator/src/resolve/resolver.ts
- tools/devworkspace-generator/src/resolve/url.ts
- tools/devworkspace-generator/src/types.ts
- tools/devworkspace-generator/tests/bitbucket-server/bitbucket-server-resolver.spec.ts
- tools/devworkspace-generator/tests/bitbucket/bitbucket-resolver.spec.ts
- tools/devworkspace-generator/tests/github/github-resolver.spec.ts
- tools/devworkspace-generator/tests/inversify/inversify-binding.spec.ts
- tools/devworkspace-generator/tests/resolve/git-url-resolver.spec.ts
Add Bitbucket and Bitbucket Server support
https://issues.redhat.com/browse/CRW-4323
1. Deploy bitbucket server: https://github.com/che-incubator/git-srv/tree/main/bitbucket.
2. Create a repository with a devfile in the bitbucket server instance.
3. Go to projects directory: '/tools/devworkspace-generator' directory
4. execute `yarn`
5. execute 
```bash
node lib/entrypoint.js \
--plugin-registry-url:https://che-plugin-registry-main.surge.sh/v3/ \
--editor-entry:che-incubator/che-code/latest \
--output-file:<output directory> \
--injectDefaultComponent:true \
--defaultComponentImage:registry.access.redhat.com/ubi8/openjdk-11:latest \
--devfile-url:<url of the bitbucket server repo>
```
See: `yaml` file is generated and contains the devfile from the repository.
[As the author of this Pull …
> Add Bitbucket and Bitbucket Server support

- .github/workflows/devworkspace-generator-release.yml
- .github/workflows/release.yml
- make-release.sh
- tools/devworkspace-generator/package.json
Che Devworkspace Generator (here Generator) shall be assigned a che version pattern, so that a che-version artifact will be produced on release (to be used in other che projects, that depend on it).
In main branch, current 0.0.1 version will be changed to next "would-be-released" version, similarly to how it is done in plugin registry.
UPDATE:
Created a separate workflow for releasing just the Generator, which could be performed in the first phase of Che release cycle, so that the projects that depend on it could be released in the following phases ASAP. Release tagging of repo will occur in Devfile Registry release workflow
https://github.com/eclipse/che/issues/22279
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-requ …
> feat: Add devworkspace-generator to Che release cycle

- tools/devworkspace-generator/src/generate.ts
- tools/devworkspace-generator/tests/generate.spec.ts
Add a logic to analyze a original devfile if it contains a section with `starterProjects`  into devworkspace generator tool. If it contains, we add `controller.devfile.io/use-starter-project` attribute with value that describes the name of the project:
```
spec:
template:
attributes:
controller.devfile.io/use-starter-project: name-of-the-project
```
After applying generated devworkspace the project should be cloned into the workspace and should be available in the Project tree.
An example of the generated devworkspace:
<details>
<summary>Original devfile:</summary> 
```yaml
schemaVersion: 2.1.0
metadata:
name: nodejs-svelte
displayName: Svelte
description: "Svelte is a radical new approach to building user interfaces.
Whereas traditional frameworks like React and Vue do the bulk of their …
```
> feat: add an attribute with starterProject to the devworkspace

- deploy/openshift/che-devfile-registry.yaml
Fix deployment configuration for OpenShift
https://github.com/eclipse/che/issues/20133
1. Login into OS cluster
2. Execute command from README to deploy che plugin registry:
```bash
oc new-app -f deploy/openshift/che-devfile-registry.yaml \
-p IMAGE="quay.io/eclipse/che-devfile-registry" \
-p IMAGE_TAG="next" \
-p PULL_POLICY="Always"
```
3. Devfile registry should be deployed and available. In the output you should see a message:
```
--> Success
Access your application via route 'che-devfile-registry-pr.apps.rosa.dzhix-cyddx-yrv.1697.p3.openshiftapps.com' 
Run 'oc status' to view your app.
```
4. Try to open route URL from the message and add **/devfiles** at the end
5. You should see:
[As the author of this Pull Request I made sure …
> chore: update registry deployment configuration

- .github/workflows/release.yml
- make-release.sh
Updates make-release.sh to use gh instead of hub.
https://github.com/eclipse/che/issues/22646
> Fix: Change from hub to gh for Che #22646
