devfiles/apache-camel-springboot-che7/devfile.yaml
devfiles/java-gradle/devfile.yaml
devfiles/java-maven/devfile.yaml

Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Updates java-based devfiles to use latest version of redhat-java plugin
https://github.com/eclipse/che/issues/13378

Change version of redhat-java plugin to latest

---

devfiles/apache-camel-springboot-che7/devfile.yaml
devfiles/dotnet/devfile.yaml
devfiles/go/devfile.yaml
devfiles/java-gradle/devfile.yaml
devfiles/java-maven/devfile.yaml
devfiles/python/devfile.yaml

`$TITLE`
https://github.com/eclipse/che/issues/13336

Update the devfiles to the latest version of the devfile schema.

---

devfiles/apache-camel-springboot-che7/devfile.yaml
devfiles/dotnet/devfile.yaml
devfiles/go/devfile.yaml
devfiles/python/devfile.yaml

Make devfiles in regisrtry use latest versions of plugins

Use latest versions of plugins in devfiles

---

README.md
build.sh
deploy/kubernetes/che-devfile-registry/values.yaml
deploy/openshift/che-devfile-registry.yaml

Updates default image to quay.io/openshiftio/che-devfile-registry
Improve readme
N/A

 Update default image to quay.io/openshiftio/che-devfile-registry && Improve readme

---

deploy/kubernetes/che-devfile-registry/templates/ingress.yaml

Fix the deployment error when he/she uses Helm and sets TLS enable.
None.

Fix invalid indents.

---

devfiles/apache-camel-springboot/devfile.yaml
devfiles/dotnet/devfile.yaml
devfiles/java-gradle/devfile.yaml
devfiles/java-maven/devfile.yaml
devfiles/nodejs/devfile.yaml
devfiles/python-django/devfile.yaml
devfiles/python/devfile.yaml

This PR moves the working directory to a dedicated field instead of using 'cd' command.
It makes commands shorter and obvious.
Devfiles are not tested after changes but it should not break anything.
N/A

Moved working directory to a dedicated field instead of using 'cd' command

---

devfiles/python-django/devfile.yaml

Fix typo in python-django stack

---

README.md

Adding ci nightly build icon to README
N/A

Adding ci nightly build icon to README

---

VERSION

Adding test commit to the release branch

---

VERSION

Adding a test commit to verify the release CI

Adding a test commit to verify the release CI

---

VERSION

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

Testing release version

---

cico_functions.sh

Build and push arbitrary-user patched images to 'eclipse' quay.io organization only
Fixing master CI - https://ci.centos.org/job/devtools-che-devfile-registry-build-master/

Build and push arbitrary-user patched images to 'eclipse' quay.io organization only

---

devfiles/java-mysql/devfile.yaml

Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
- Adds a new command to configure database
- Fixes the command to run the application 
https://github.com/eclipse/che/issues/13938

Add a command to configure db. Fix spring profile to run application

---

devfiles/dotnet/devfile.yaml

Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Makes it possible to debug an application by adding several improvements:
-  The project was updated, now it is using netcoreapp2.2
-  Added a command to build the project. It is needed to be run before running debug
- Predefined debug configuration
https://github.com/eclipse/che/issues/14090
https://youtu.be/0xYFGMwPxPc

Fix devfile for dotnet

---

devfiles/nodejs/devfile.yaml

Enhancement: Add stop nodejs server command.

Improve node.js devfile

---

devfiles/php-web-simple/devfile.yaml

Adding restart command to the 'php-web-simple' devfile
related to https://github.com/redhat-developer/rh-che/issues/1434

Adding restart command to the 'php-web-simple' devfile

---

arbitrary-users-patch/base_images

Add image with golang 1.12 for plugin broker devfile.
https://github.com/eclipse/che/issues/14126

Add image with golang 1.12 for plugin broker devfile.

---

README.md

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

Readme change to trigger the build

---

devfiles/go/devfile.yaml

Add a command to run arbitrary go file.
https://github.com/eclipse/che/issues/14007

Add task to run any file

---

README.md

Adding status for `promote-to-prod-preview` CI job and documentation for all existing CI jobs used in devfile regsitry
N/A

Adding status for `release-preview` CI job and documentation for all existing CI jobs used in devfile regsitry

---

.github/CODEOWNERS

Add myself as a codeowner for this repo now that we're not in code freeze.

Add amisevsk to codeowners

---

cico_functions.sh

Cherry-pick 2b689e3 into release branch

---

devfiles/nodejs-mongo/devfile.yaml

Updates stack for developing nodeJS+mongoDB web application. 
The application is https://github.com/che-samples/nodejs-mongodb-sample
The demo about how it works: https://youtu.be/UYTpVw2uasI
https://github.com/eclipse/che/issues/14392

Update NodeJS-MongoDB devfile to use new sample

---

devfiles/java-gradle/devfile.yaml
devfiles/java-maven/devfile.yaml

Use sample branch with java11
none

Use java 11 ready sample

---

devfiles/nodejs/devfile.yaml

Fix debug configuration

---

build/dockerfiles/Dockerfile
build/dockerfiles/rhel.Dockerfile
build/scripts/list_referenced_images.sh
devfiles/java-mysql/devfile.yaml
devfiles/nodejs-mongo/devfile.yaml
devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml

Minor fixes to airgap support
- In `list_referenced_images.sh`, get all images, no matter where they're referenced
- Update all devfiles to list images with registry included.

Improve airgap support

---

devfiles/java-mongo/devfile.yaml
devfiles/java-mongo/meta.yaml

Adds new devfile with [java-guestbook](https://github.com/svor/java-guestbook) sample. It is a java web application with Spring Boot and MongoDB which is based on [Google Cloud Sample](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-guestbook) and can be deployed on k8s cluster.
https://github.com/eclipse/che/issues/14651

Add devfile with java sample based on google cloud sample 

---

deploy/kubernetes/che-devfile-registry/templates/configmap.yaml

Fix a typo in the helm chart that stops it from being parsed.
https://github.com/eclipse/che/issues/14994

Fix a typo in the helm chart

---

build/dockerfiles/rhel.Dockerfile

Change-Id:...
move to latest upstream images
Change-Id: I9fa93a2e662428c2bc65ef4aeee1584ac0153071

move to latest upstream images

---

build/dockerfiles/rhel.Dockerfile

Change-Id:...
latest base images
Change-Id: I9bc8414ae789157a64036fa4e82635ca5d2d3731

latest base images

---

devfiles/java-web-vertx/devfile.yaml

Updates vert.x sample
https://github.com/eclipse/che/issues/15314

Update vert.x sample

---

arbitrary-users-patch/base_images
devfiles/rust/devfile.yaml
devfiles/rust/meta.yaml

Adds devfile for rust support. This does yet include the VS code plugin for rust, due to trouble getting it to work properly.

Add devfile and base image for rust

---

devfiles/java-mysql/devfile.yaml
devfiles/java-web-spring/devfile.yaml

fixes eclipse/che#15483.
fixes eclipse/che#15483.
Enable to build `offilne-registry`.
eclipse/che#15483.

Remove unsuitable tab chars.

---

devfiles/nodejs-yarn/devfile.yaml
devfiles/nodejs-yarn/meta.yaml

Adds a new devfile which contains sample based on yarn. The sample is React App generated by https://github.com/facebook/create-react-app and its location is https://github.com/che-samples/react-web-app.git. 
The provided commands are:
- install all required dependencies
- build the app
- run the app
- launch tests
https://github.com/eclipse/che/issues/14720

Add new devfile with sample based on yarn

---

devfiles/apache-camel-springboot/devfile.yaml

as the new version 0.0.20 requires an higher value

Change memory required for Apache Camel

---

README.md

Update the README.md instructions for building the registry to refer to the build.sh script.

Update README.md build instructions to use build.sh script

---

RELEASE.md

Adding RELEASE.md file with instructions for Major / Minor and Service / Bugfix  releases
https://github.com/eclipse/che/issues/15506

che #15506 Adding RELEASE.md file with instructions for Major / Minor and Service / Bugfix  releases

---

build/dockerfiles/rhel.Dockerfile

Change-Id:...
update base images
Change-Id: I4e2fa1552111a53f1a148670d87ee3a4e470677e

update base images

---

arbitrary-users-patch/build_images.sh
arbitrary-users-patch/happy-path/build_happy_path_image.sh
cico_functions.sh

Attempts to remove unnecessary logs from CI builds (progress bars, etc).

Reduce verbosity in CI builds

---

devfiles/java-mysql/devfile.yaml

Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR fixes an issue with the devfile's tasks that occured because of changes in the upstream version of the petclinic project. It also pins the java-mysql devfile to a specific commitId so that this won't happen again.
Fixes: https://github.com/eclipse/che/issues/15852
Reference: https://github.com/eclipse/che/issues/15898

Fixes java-mysql tasks for latest version of petclinic

---

build/scripts/write_image_digests.sh

Cherry-pick commit f5c7af1 (PR https://github.com/eclipse/che-devfile-registry/pull/207)
eclipse/che#16281

Don't rewrite image digests for images we can't read (#207)

---

.github/CODEOWNERS

Update CODEOWNERS to reflect team change

---

devfiles/go/devfile.yaml

Cleanup Go debug configuration

Cleanup Go debug configuration

---

devfiles/che4z/devfile.yaml
devfiles/che4z/meta.yaml

Updated Zowe components. Updated description.
Signed-off-by: Filip Kroupa <filip.kroupa@broadcom.com>
Updated images with latest version of Zowe Explorer and Zowe CLI
Updated stack description
Related to eclipse/che-plugin-registry#416
Targetting [Milestone 7.10.0](https://github.com/eclipse/che/milestone/113)

Che4z-1.2.0

---

build/dockerfiles/Dockerfile

It replaces centos/httpd with alpine/httpd allowing to be smaller/updated and also multi-arch
Change-Id: I3b9802799fcd05bb388b4fcd3ffa14a6424a8a9e

feat(alpine): Change parent image to be alpine based as well

---

devfiles/apache-camel-springboot/devfile.yaml
devfiles/go/devfile.yaml
devfiles/java-mysql/devfile.yaml
devfiles/java-web-spring/devfile.yaml
devfiles/java-web-vertx/devfile.yaml
devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml
devfiles/php-web-simple/devfile.yaml

Fix for https://github.com/eclipse/che/issues/16748
root bug: https://github.com/eclipse/che/issues/16381

Quick fix all endpoints name

---

devfiles/quarkus/devfile.yaml

try it: http://che.openshift.io/factory?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/a1ea5f8915fad9b582be5c347b767ee555f14053/devfiles/quarkus/devfile.yaml

Enabling quarkus native compilation

---

devfiles/scala-sbt/devfile.yaml
devfiles/scala-sbt/meta.yaml

Signed-off-by: sideeffffect <ondra.pelech@gmail.com>
depends on Scala language server being available: https://github.com/eclipse/che-plugin-registry/pull/356
/cc @ibuziuk @svor

Add Scala/sbt devfile

---

devfiles/nodejs-mongo/devfile.yaml

Updates mongodb endpoint to fix a problem with starting the application.
**Depends on** https://github.com/che-samples/nodejs-mongodb-sample/pull/3

Update mongodb endpoint

---

devfiles/nodejs-mongo/devfile.yaml
devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs/devfile.yaml
devfiles/nodejs/meta.yaml

Adds node-debug plugin into stacks with node debug configuration
Depends on https://github.com/eclipse/che-plugin-registry/pull/506
https://issues.redhat.com/browse/CRW-997

Add node-debug plugin into nodejs stacks with debug configuration

---

deploy/kubernetes/che-devfile-registry/templates/_template.tpl
deploy/kubernetes/che-devfile-registry/templates/configmap.yaml
deploy/kubernetes/che-devfile-registry/templates/ingress.yaml
deploy/kubernetes/che-devfile-registry/values.yaml

1. Reduce environment variables that have empty string. (similar to https://github.com/eclipse/che-plugin-registry/pull/369 )
2. Add value `hostnameOverride`. This is for shared devfile-registry.
None.

Helm chart improvements

---

arbitrary-users-patch/base_images
devfiles/dotnet/devfile.yaml
devfiles/dotnet/meta.yaml

Updates existing .NET Core devfile to use dotnet 3.1.301
https://github.com/eclipse/che/issues/17045

Update dotnet devfile to use dotnet 3.1

---

deploy/kubernetes/che-devfile-registry/templates/_template.tpl

I offer this quick fix of a problem I've run into. Issue is mentioned.
https://github.com/eclipse/che/issues/17372
Signed-off-by: Filip Kroupa <filip.kroupa@broadcom.com>

Fix _template.tpl

---

devfiles/quarkus-command-mode/meta.yaml
devfiles/quarkus/meta.yaml

Clarify the Quarkus stack titles + descriptions

---

devfiles/python-django/devfile.yaml
devfiles/python-django/meta.yaml
devfiles/python/devfile.yaml
devfiles/python/meta.yaml

Update python 3.8.6 and a more recent version of vscode-python
https://github.com/eclipse/che/issues/16183
related PRs: 
* https://github.com/eclipse/che-devfile-registry/pull/294
* https://github.com/eclipse/che-plugin-registry/pull/641
* https://github.com/che-samples/django-realworld-example-app/pull/1

Update devfiles to user 3.8.6 version of python stuff

---

devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml
devfiles/php-web-simple/devfile.yaml

Removes references to old plugins in the PHP stack.
N/A
N/A
N/A

Remove references to old PHP plugins

---

devfiles/java-mongo/devfile.yaml
devfiles/nodejs-mongo/devfile.yaml
devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml

Enables the persistence for databases
https://github.com/eclipse/che/issues/18322

Allow to persist databases

---

devfiles/php-symfony/devfile.yaml

Use `main` branch on `symfony/demo.git`
None
None
1. Just building for the offline mode without this PR.
2. Builds are failed.
3. Apply this PR.
4. Builds are succeeded.

Fix the branch of symfony/demo.

---

devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml
devfiles/php-web-simple/devfile.yaml

Fixes id of php-debug plugin
https://github.com/eclipse/che/issues/18493

Fix id of php-debug plugin

---

.github/workflows/release.yml

Add workflow dispatch trigger to the release job, to attempt to run it manually, since branch trigger doesn't work for some reason (maybe quotes will help?)

Add manual release job trigger

---

.github/workflows/release.yml

Add parameter to the workflow dispatch trigger

Add parameter to manual release job trigger

---

deploy/kubernetes/che-devfile-registry/templates/_template.tpl
deploy/kubernetes/che-devfile-registry/templates/ingress.yaml
deploy/kubernetes/che-devfile-registry/values.yaml
deploy/openshift/che-devfile-registry.yaml

Signed-off-by: Anatolii Bazko <abazko@redhat.com>
Update OpenShift templates to be able to deploy on OCP cluster with support of TLS
https://issues.redhat.com/browse/RHDEVDOCS-2483

Update OpenShift templates

---

.github/workflows/nightly-build-publish.yml
.github/workflows/pr-checks.yml
.github/workflows/release.yml
PLATFORMS

Adds PLATFORMS file rather than mentioning platforms in multiple .yml files. Also, adds 2 more platforms, i,e ppc64le and arm64.
This is a follow-up PR to implement review comments provided by @benoitf on #321 .

Adds platforms file for buildx

---

devfiles/bash/devfile.yaml
devfiles/bash/meta.yaml

Add bash devfile
none.
Create new workspace from devfile

Add bash devfile.

---

.github/workflows/nightly-build-publish.yml
.github/workflows/pr-checks.yml
.github/workflows/release.yml
PLATFORMS

Removes multi-arch support temporarily, it's failing for a release and we don't have time to investigate it today.
This reverts commit e06ad661ac45375da8021de81064b9914bf30275.
This reverts commit e1b97e63f0edc68ee088174d890f5a06f51025ed.
N/A
N/A
Run the release job manually and verify that it's working.

Revert multi-arch support

---

arbitrary-users-patch/base_images
devfiles/python/devfile.yaml

Ensure all Python devfiles use 3.8 and remove 3.7 from base images list.
Fixes eclipse/che#18794
Run the python-simple workspace and verify that the commands work as expected.

Ensure all Python devfiles use 3.8

---

devfiles/quarkus/devfile.yaml
devfiles/quarkus/didact.md

Add a didact guide to the Quarkus get started devfile.
Part of https://github.com/eclipse/che/issues/18197
To try it, it needs a Che plugin registry container built from this branch.
This one could be used: `quay.io/sunix/che-devfile-registry@sha256:cceeb59d3e066ebbc657a23429b858167431190d44de5a5def66dacb335f7f35`
For instance:
```
kubectl edit CheCluster/eclipse-che -n che
```
and 
```yaml
devfileRegistryImage: quay.io/sunix/che-devfile-registry@sha256:cceeb59d3e066ebbc657a23429b858167431190d44de5a5def66dacb335f7f35
```
edit: with the offline build:
```yaml
devfileRegistryImage: quay.io/sunix/che-devfile-registry@sha256:3c7c0618db5f64799b59953f27d6305a19efd0f01c68e9be30178362a3caddf0
```
Then start a new workspace with the "Quarkus Rest API" devfile:
[As the author of this Pull Request I …

feat(quarkus-didact): adding a vscode-didact guide to the Quarkus get started devfile.

---

devfiles/apache-camel-springboot/devfile.yaml
devfiles/bash/devfile.yaml
devfiles/dotnet-asp.net/devfile.yaml
devfiles/dotnet/devfile.yaml
devfiles/go/devfile.yaml
devfiles/java-mongo/devfile.yaml
devfiles/java-mysql/devfile.yaml
devfiles/java-web-spring/devfile.yaml
devfiles/nodejs-mongo/devfile.yaml
devfiles/nodejs-react/devfile.yaml
devfiles/nodejs-yarn/devfile.yaml
devfiles/nodejs/devfile.yaml
devfiles/php-laravel/devfile.yaml
devfiles/php-mysql/devfile.yaml
devfiles/php-symfony/devfile.yaml
devfiles/php-web-simple/devfile.yaml
devfiles/python-django/devfile.yaml
devfiles/python/devfile.yaml

Removes memory limitations for plugins as the limitation for the plugin is set in plugin meta.yaml.
Align with https://github.com/eclipse/che/issues/16685

Remove Memory limitations for plugins

---

build/scripts/cache_projects.sh
devfiles/lombok/devfile.yaml
devfiles/lombok/meta.yaml
images/lombok.svg

Provide a lombok stack with.
- a sample project
- the Java plugin properly configured
https://github.com/eclipse/che/issues/17483
I have pushed a devfile registry with these changes in surge.sh. To test it, update the CheCluster CR with:
```
devfileRegistryUrl: https://sunix-che-devfile-registry-lombok-qpd6g.surge.sh
externalDevfileRegistry: true
```
Wait for the dashboard to reload.
Some problems you may have while testing:
- you may need to disable CORS: `chromium-browser --disable-web-security --user-data-dir=/tmp/chromium-tmp-user-data-cors`
- the devfile requires https://github.com/eclipse/che-plugin-registry/pull/871 So if your are not using nightly nor 7.28, update the plugin with the registry-url in the devfile:
```yaml
- id: redhat/java/latest
preferences:
java.jdt.ls.vmargs: …
```

feat(lombok-devfile): Add lombok devfile

---

.github/workflows/release.yml

fetch depth:0 or you don't get any tags
Change-Id: Idf7c30eb08cc469d7a4ab1c0982010ff30752047
N/A
N/A

fetch depth:0 or you don't get any tags

---

make-release.sh

can't popd out of a folder if we never when in there in the first place
Change-Id: Ia1e24bc86447f73903a058dd50578a60c4b8895c
N/A
N/A

bug(fix): can't popd out of a folder if we never when in there in the first place

---

arbitrary-users-patch/base_images

Upgrade GraalVM version to work with Quarkus latest version
https://github.com/eclipse/che/issues/19352

fix(quarkus-devfile): Fix Quarkus native compile using GraalVM 21.0

---

deploy/openshift/che-devfile-registry.yaml

Use tls for external devfile registry deployment on the Openshift.
none
none. I played with external registry options and this quick fix.
Deploy external devile registry to the namespace `che-registries`:
```
$ oc new-project che-registries
$ oc new-app -f deploy/openshift/che-devfile-registry.yaml -p IMAGE="quay.io/eclipse/che-devfile-registry" -p IMAGE_TAG="nightly" -p PULL_POLICY="Always" -n che-registries
```
Deploy Che using external registry:
```
$ chectl server:start -p openshift -n moon40 --devfile-registry-url=https://che-devfile-registry-che-registries.apps-crc.testing
```
Go to quick start tab on the user dashboard. List devfiles should be displayed.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-tem …

Use tls for external devfile registry deployment on the Openshift.

---

devfiles/quarkus-command-mode/devfile.yaml

Signed-off-by: Sun Tan <sutan@redhat.com>
Fix command using the version 1.0.0-SNAPSHOT instead of 1.0-SNAPSHOT (quarkus sample changes)
https://github.com/eclipse/che/issues/18982

fix(quarkus-cli): update native executable name in Start Native command

---

.github/workflows/release.yml

Fixes for release workflow
- Use v2 version of checkout, so that authentication works for git pushes 
- Fetch all history when checking out

Release checkout fix

---

.github/workflows/release.yml
RELEASE.md
deploy/kubernetes/che-devfile-registry/Chart.yaml
deploy/kubernetes/che-devfile-registry/README.md
make-release.sh

Adapts the `make-release.sh` script to use the new org, pending confirmation on: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958
Part of eclipse/che#19388

Adapt make-release.sh to use the eclipse-che org

---

arbitrary-users-patch/base_images

Updates the digest for the quarkus image.
Fixes the `7.29.0` release.
Checkout the brand and try to run `arbitrary-users-patch/build_images.sh`

Update quarkus digest

---

arbitrary-users-patch/base_images

Updates the quarkus digest.
N/A
Unblocks the 7.29.1 release.
Release script and PR checks will be green.

Update quarkus digest (again)

---

.ci/generate_and_publish_registry_url_devfiles.sh
.github/workflows/release.yml

Generates devfiles with `registryUrl` fields and publishes them on GitHub pages. For example, the URL of the `7.29.1` devfile registry hosted on GitHub pages will be `eclipse-che.github.io/che-devfile-registry/7.29.1/`
N/A
Fixes eclipse/che#19269
Run the script with your GitHub token and `VERSION` set to a valid tag, and observe the `gh-pages` branch of this repo.

Publish devfiles with registryUrls to GH pages

---

.ci/generate_and_publish_registry_url_devfiles.sh

Runs `entrypoint.sh` on the devfiles that are published to GitHub pages.
N/A
Part of eclipse/che#19269
Run the `.ci/generate_and_publish_registry_url_devfiles.sh` script and observe that the correct devfile registry URL is substituted into the Quarkus devfile.

Run entrypoint on devfiles published to GitHub pages

---

arbitrary-users-patch/base_images

Using a digest has proven to be unstable. Revert to using a tag until a better solution is found.
N/A
N/A
Building the base images should work.

Use the centos-quarkus-maven:21.0-java11 tag

---

.github/workflows/release.yml

- add yq that is required for new devfile generation script
- add flags `performRelease` and `publisDevfilesToGhPages` to be able to enable/disable these steps when rerunning the release workflow

Fixes for release workflow

---

devfiles/go/devfile.yaml

Enabling multiroot for go devfile.
fixing https://github.com/eclipse/che/issues/19476
1. Add the generated plugin-registry with the fix to your che cr cluster configuration:
```
devfileRegistryUrl: https://sunix-che-devfile-registry-go-multiroot-jqo2j.surge.sh/
externalDevfileRegistry: true
```
and once it is redeployed, start the workspace from the go stack.
2. check that it is working fine (code completion on go files, etc ...)

fix(go-lang): fix and enable multiroot for golang stack

---

.github/workflows/release.yml

Unblock the release by installing the correct yq version in the GitHub action runner.
N/A
Run the Release workflow.

Install mikefarah yq

---

.github/workflows/release.yml

Use `with: cmd:` instead of `run`
N/A
Unblocks the 7.30 release.

Fix release.yml syntax

---

.github/workflows/release.yml

Add quotes in if condtions strings to make it work

Fix release workflow conditions

---

.github/workflows/release.yml

Install yq using wget
Hopefully unblocks the release this time.

Install yq the old fashioned way

---

.ci/generate_and_publish_registry_url_devfiles.sh

Don't delete the `devfileRegistry` container because it won't exist on GitHub actions.
Unblocking the 7.30 release.
Release workflow should pass.

Don't remove container as it won't exist

---

arbitrary-users-patch/base_images

Updates the PHP base image to the latest version. https://github.com/che-dockerfiles/che-php-base/commit/9c00f7af1cca7bccad65e5e88565fd109eca3ecf
N/A
Fixes eclipse/che#19675

Update PHP7 base image

---

build/dockerfiles/rhel.Dockerfile

Change-Id: I72990e92243984e5d92badc5b7452a9f944af185
[base] Update from ubi8-minimal:8.2-267 to ubi8-minimal:8.3-298.1618432845
Change-Id: I72990e92243984e5d92badc5b7452a9f944af185

[base] Update from ubi8-minimal:8.2-267 to ubi8-minimal:8.3-298.1618432845

---

build/dockerfiles/rhel.Dockerfile

Change-Id: I199c896d9c5cfd2371ee72c26807c13c8bf0944b
[base] Update from ubi8-minimal:8.3-298.1618432845 to ubi8-minimal:8.4-200
Change-Id: I199c896d9c5cfd2371ee72c26807c13c8bf0944b

[base] Update from ubi8-minimal:8.3-298.1618432845 to ubi8-minimal:8.4-200

---

devfiles/python-django/devfile.yaml
devfiles/python/devfile.yaml

Python plugin is now using a dedicated venv folder stored in a volume. See https://github.com/eclipse-che/che-plugin-registry/pull/965 and https://github.com/eclipse-che/che-plugin-registry/pull/958
This is updating all the dev containers and commands to use the same venv folder:
- No need to setup the venv anymore: it is already done
- It should be faster as venv is no longer in the project tree and files are no longer being watched with no reason.
Fix https://github.com/eclipse/che/issues/19806
Related to https://github.com/eclipse/che/issues/16818
Try the python and python-django devfiles from this registry: https://sunix-che-devfile-registry-xto87.surge.sh/
The python and python-django devfiles in this registry are exactly the one from this PR but using the master branch of the plugin …

feat(python): Optimizing python devfiles by using a dedicated venv volume

---

build/scripts/index.sh
devfiles/java-web-spring/meta.yaml

Provides v2 links for devfile v2
For now add only one entry for spring petclinic
https://github.com/eclipse/che/issues/19906
check existing links are working (as yq is used to update links)
Try out the spring petclinic devfile v2 with DevWorkspace enabled Che
Change-Id: I769f8013065249674b35748176ef8acdf847f671

feat(devfile): Add a new link entry for devfile v2

---

.github/workflows/next-build.yml

Publish to GH pages on every commit merged to master.
Fixes eclipse/che#19779
N/A

feat(gh-pages): publish a master version of the devfile registry

---

.github/workflows/next-build.yml

Installs yq at the end of the next-build GitHub actions job, so that the publish to GitHub actions succeeds.
eclipse/che#19779
Run the next-build GH action job on this PR branch and see that it succeeds.

fix(gh-pages): install yq in next-build job

---

README.md

Adds information to the README about the published versions of the devfile registry.
eclipse/che#19779
Look at the rendered README content

Update README with published registry info

---

devfiles/che4z/devfile.yaml

Make VSCode extension 'COBOL Control Flow' part of 'Mainframe Basic Stack' devfile
CCF was introduced into plugin registry by this [PR 992](https://github.com/eclipse-che/che-plugin-registry/pull/992)
- Create new workspace from Mainframe Basic Stack
- Workspace starts and loads CCF plugin. Logs should contain these lines:
```
...
List of plugins and editors to install
...
- broadcommfd/ccf/latest - Extension for cobol control flow
...
All plugin metadata has been successfully processed
...
Processing plugin broadcommfd/ccf/latest
Installing plugin extension 1/1
Downloading plugin from https://open-vsx.org/api/BroadcomMFD/ccf/0.4.0/file/BroadcomMFD.ccf-0.4.0.vsix
...
All plugin artifacts have been successfully downloaded
...
```
- Check CCF plugin is available in workspace
[As the author …

feat: Add COBOL Control Flow to Mainframe Basic Stack

---

devfiles/quarkus/meta.yaml

Add a devfile V2 for quarkus as well
Using devWorkspaces enabled workspace
Use as factory link https://github.com/che-samples/quarkus-quickstarts/tree/devfilev2
Change-Id: I08df035e1519dda7d9e1911f9b7ed8cd001023ec

feat(v2): Introduce quarkus

---

arbitrary-users-patch/build_images.sh
arbitrary-users-patch/happy-path/build_happy_path_image.sh
make-release.sh

All images that are created during release with release tag, will also be pushed as "latest" images (similarily to how it is in other Che projects)
https://github.com/eclipse/che/issues/19875
Run the workflow when it's merged

ci: Push images with latest tags during release

---

.github/workflows/update-latest-images.yml

Fixes for the "Update base images" workflow
- add missing components ( yq ), and increase the speed of dependency installation
- fix missing github token
- enable the job to run weekly
https://github.com/eclipse/che/issues/18831
the workflow with this content has been run in a test branch

fix: fixes for the Update base images workflow

---

devfiles/nodejs-angular/devfile.yaml
devfiles/nodejs-mongo/devfile.yaml
devfiles/nodejs-react/devfile.yaml
devfiles/nodejs-yarn/devfile.yaml
devfiles/nodejs/devfile.yaml

Do not use the old `che-incubator` typescript plugin definition.
N/A
Start the affected devfiles and observe that they still work.

fix(devfiles): update typescript plugin definition

---

devfiles/nodejs-angular/devfile.yaml

Bump the memory limit for the angular JS devfile based on feedback from users.
N/A
Run the devfile and observe that it doesn't run out of memory.

Update angular devfile memory limit

---

arbitrary-users-patch/base_images

Fixes digest for quarkus base image 
N/A
N/A
Check build results

fix: update digest for centos-quarkus-maven image

---

devfiles/che4z/devfile.yaml

Update Zowe CLI docker images.
- latest Zowe CLI updates
- new docker registry
Start new workspace from Mainframe Basic Stack (che4z). If workspace starts correctly, docker images were pulled successfully.

fix(che4z): update Zowe CLI docker images

---

devfiles/java-mongo/devfile.yaml

chore: update to latest che--centos--mongodb-36-centos7:latest-ffdf2431bbc6d9a9d2a03e95bbbe8adb49ab9eac301f268a35038c84288259c1
Change-Id: Ifd77036bf654192a61204effe35a345cbbf7d09a
N/A
https://github.com/eclipse/che/issues/20147
N/A

chore: update to latest che--centos--mongodb-36-centos7:latest-ffdf2431bbc6d9a9d2a03e95bbbe8adb49ab9eac301f268a35038c84288259c1

---

.ci/generate_and_publish_registry_url_devfiles.sh

After git add, need to use --staged flag to see if there are changes
Else current script was not seeing any changes and then did not push to gh pages
https://github.com/eclipse/che/issues/20224
launch the command `git diff --staged --quiet` and see that it detects changes
Change-Id: I368b49a2827821297a7e7ae98c9d2b541dca475f

chore(gh-pages): Fix publication script

---

README.md

We only have 'next' builds, no longer 'nightlies'
https://github.com/eclipse/che/issues/18510
Check readme icons

chore(status): remove nightly build

---

.htaccess

When registry is private, e.g. behind oauth2-proxy, it requires cookies to access.
https://github.com/eclipse-che/che-dashboard/pull/333
Set spec.server.devfileRegistryImage to ghcr.io/mtsmfm/che-devfile-registry:394adb8 (an image which contains this patch)

feat: Support CORS with credentials

---

.htaccess

Revert PR #466 
see comments in the PR

chore(revert): revert PR #466

---

devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs/meta.yaml

Provides v2 links for devfile v2 in nodejs and nodejs-mongo stacks
Try out nodejs and nodejs-mongo devfiles v2 with DevWorkspace enabled Che

feat(devfilev2): provide links to devfile v2 for nodejs and nodejs-mongo

---

devfiles/python/meta.yaml

Provides v2 link for devfile v2 in python stack
Try out python devfile v2 with DevWorkspace enabled Che

feat(devfilev2): add a link to python hello-world devfile version 2

---

README.md

There is no longer nightly jobs, only jobs triggered after each commit to the main branch
N/A
Check README before and after,
before: image is not displayed and link name is invalid
after: link title is displayed and nightly link is gone

docs: fix links of jobs

---

.github/workflows/build-sidecar-images-on-push.yml
build/workflows/bump-devfiles-to-new-sidecar-tags.sh
dockerfiles/base.dockerfile
dockerfiles/build.sh
dockerfiles/java8-maven/Dockerfile
dockerfiles/quarkus/Dockerfile

Fixes creating of pull request after bumping the devfiles to new sidecar tags.
Fixup for https://github.com/eclipse-che/che-devfile-registry/pull/464
no screenshot
https://github.com/eclipse/che/issues/19695

chore(sidecar-images): fix bumping of devfiles to new sidecar tags

---

devfiles/go/devfile.yaml

chore: 20610 - move to golang-1.17:6e0c053
Change-Id: Ie13c3c8e1c58cc115fc88e484782dc6b058f0d52
N/A
N/A

chore: 20610 - move to golang-1.17:6e0c053

---

devfiles/python-django/meta.yaml

Provides v2 link for devfile v2 in python-django stack
Try out python-django devfile v2 with DevWorkspace enabled Che

feat(devfilev2): add a link to python django devfile version 2

---

make-release.sh

Properly handles the exitstatus of grep command execution on devfiles, that don't use sidecars
https://github.com/eclipse-che/che-devfile-registry/runs/3952345311?check_suite_focus=true
Part of https://github.com/eclipse/che/issues/19695
Run `make-release.sh` script locally.

chore(make release): catch exitstatus of grep command

---

devfiles/java-mongo/meta.yaml

Adds devfile V2 link for java-mongo sample.
Build the devfile registry by hands and then use it within your Che deployment.

chore(devfile2): add devfile2 link for java-mongo sample

---

.github/workflows/try-in-web-ide.yaml

[Adds the Try in Web IDE GitHub action]( https://github.com/marketplace/actions/try-in-web-ide)
N/A
https://github.com/eclipse/che/issues/20664
N/A

feat: add try-in-web-ide GH action

---

devfiles/nodejs-yarn/meta.yaml

Introduce devfile version 2 for nodejs+yarn stack
Try to run DevWorkspace by using factory with https://github.com/che-samples/react-web-app/tree/devfilev2 

chore: Add link to devfile version 2

---

.github/CODEOWNERS

chore(codeowners): remove @sunix from codeowners

---

devfiles/cpp/meta.yaml
devfiles/nodejs-angular/meta.yaml
devfiles/nodejs-react/meta.yaml

Adds links to cpp, nodeJs+React and nodeJs+Angular devfiles
React:
Angular:
CPP:
Try to run DevWorkspace by using a factory with next links:
-  https://github.com/che-samples/nodejs-react-redux/tree/devfilev2 - NodeJS + React
-  https://github.com/che-samples/nodejs-angular/tree/devfilev2 - NodeJS + Angular
-  https://github.com/che-samples/cpp-hello-world/tree/devfilev2 - CPP  

chore: introduce a few devfiles v2

---

devfiles/scala-sbt/meta.yaml

(feature) Scala: add link to v2 devfile

---

devfiles/php-symfony/meta.yaml

Adds a link to PHP + Symphony devfile
Try to run DevWorkspace by using a factory with this sample:
https://github.com/che-samples/php-symfony/tree/devfilev2. 
All commands from workspace view should work and features from php vscode-intelephense plugin

chore: Add link to php-symphony devfile 2

---

devfiles/apache-camel-k/meta.yaml
devfiles/apache-camel-springboot/meta.yaml
devfiles/bash/meta.yaml
devfiles/che4z/meta.yaml
devfiles/cpp/meta.yaml
devfiles/dotnet-asp.net/meta.yaml
devfiles/dotnet/meta.yaml
devfiles/go/meta.yaml
devfiles/java-gradle/meta.yaml
devfiles/java-lombok/meta.yaml
devfiles/java-maven/meta.yaml
devfiles/java-mongo/meta.yaml
devfiles/java-mysql/meta.yaml
devfiles/java-web-spring/meta.yaml
devfiles/java-web-vertx/meta.yaml
devfiles/nodejs-angular/meta.yaml
devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs-react/meta.yaml
devfiles/nodejs-yarn/meta.yaml
devfiles/nodejs/meta.yaml
devfiles/php-laravel/meta.yaml
devfiles/php-mysql/meta.yaml
devfiles/php-symfony/meta.yaml
devfiles/php-web-simple/meta.yaml
devfiles/python-django/meta.yaml
devfiles/python/meta.yaml
devfiles/quarkus-command-mode/meta.yaml
devfiles/quarkus/meta.yaml
devfiles/rust/meta.yaml
devfiles/scala-sbt/meta.yaml

chore: #19953 add community tag to meta.yaml files, so we can use it to label devfile tiles in the dashboard
(step 1 of https://github.com/eclipse/che/issues/19953 )
Change-Id: If07299dd452819cbd3efc0d7364d08d285e04754
N/A
https://github.com/eclipse/che/issues/19953
N/A

chore: #19953 add community tag to meta.yaml

---

devfiles/dotnet-asp.net/meta.yaml

Adds a link to devfile v2 with ASP.NET Core Web Application  
depends on https://github.com/devfile/developer-images/pull/12#event-5681036367
Try to run DevWorkspace by using a factory with this sample:
https://github.com/che-samples/aspnetcore-realworld-example-app/tree/devfilev2

chore: add link to .NET sample with devfile v2

---

devfiles/java-lombok/meta.yaml

Adds a link to devfile v2 with Java + Lombok
Depends on https://github.com/devfile/developer-images/pull/13 and https://github.com/che-samples/lombok-project-sample/pull/1
- start a devWorkspace by using https://github.com/svor/lombok-project-sample/tree/devfilev2
- open one of the java file ModelLombokValue.java, wait for java plugin to be activated
- open the outline, see the getters and setters that are not defined in the class.

chore: add link to java-lombok devfile v2

---

build/scripts/index.sh

Ensure output of meta.yaml is in yaml and not json
Fixes https://github.com/eclipse/che/issues/20828
1. build the registry image
2. launch the container `docker run --rm -it -p 8080:8080 quay.io/eclipse/che-devfile-registry:next`
3. go to http://localhost:8080/devfiles/quarkus/meta.yaml for example
4. check it's yaml content
Change-Id: Idcbe30c9f1c8ee1f0b0162a3061ee9210dd4d4cb

fix: output of meta.yaml should be yaml content

---

build/dockerfiles/Dockerfile
build/dockerfiles/rhel.Dockerfile
build/scripts/generate_devworkspace_templates.sh

Put DevWorkspace generated files directly into `/build/devfiles/{name}/` folder
N/A
https://github.com/eclipse/che/issues/20880
Build registry and check that all devWorkspace generated files are still in the devfile/{devfile_name} folder 

fix: generate devWorkspace files into /build/devfiles/{devfile_name} folder 

---

devfiles/rust/meta.yaml

Add the rust devfile v2 sample
Try to start a workspace based on https://github.com/che-samples/helloworld-rust/tree/devfilev2

Add link to devfile v2 rust sample

---

devfiles/apache-camel-springboot/meta.yaml

Add sample v2 for fuse booster example
Issue found:
https://github.com/camel-tooling/camel-lsp-client-vscode/issues/836
PR to fix:
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/837
But I think the issue is already existing for the current plug-in in the plug-in registry
using a correct fs-extra module, I'm able to see the extension 
part of https://github.com/eclipse/che/issues/19341
Click on http://che-server#https://github.com/che-samples/fuse-rest-http-booster/tree/devfilev2
with devWorkspace enabled
you can try that build, run and debug works …

feat: introduce devfile v2 for fuse rest booster

---

build/dockerfiles/Dockerfile
build/dockerfiles/rhel.install.sh
build/scripts/generate_devworkspace_templates.sh
make-release.sh

- Updates devworkspace-che-theia-latest.yaml files in release process by replacing images' tags with the release version
- Install git into rhel.Dockerfile to fix a problem with cloning projects when preparing zip files
https://github.com/eclipse/che/issues/20824
- build image: `docker buildx build --build-arg VERSION=40.1 -f ./build/dockerfiles/Dockerfile --tag che-devfele-reg:40.1 --target registry .`
- check the content of any of devworkspace-che-theia-latest.yaml files, tags should be 40.1 in DevWorkspaceTemplate 

[chore] Update devworkspace-che-theia-latest.yaml files in release process

---

build/scripts/generate_devworkspace_templates.sh

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Update the `che-theia-devworkspace-handler` to the latest version
https://github.com/eclipse-che/che-theia/pull/1271 https://github.com/eclipse-che/che-devfile-registry/pull/532
see https://github.com/eclipse-che/che-devfile-registry/pull/532

fix: Update the che-theia-devworkspace-handler package version to latest

---

build/dockerfiles/Dockerfile
build/dockerfiles/rhel.install.sh
build/scripts/generate_devworkspace_templates.sh
make-release.sh

Backports changes described in https://github.com/eclipse-che/che-devfile-registry/pull/545 into 7.40.x

chore: Update devworkspace-che-theia-latest.yaml files in the release

---

.ci/generate_and_publish_registry_url_devfiles.sh

publish zip samples when publishing to github.io
Fixes https://github.com/eclipse/che/issues/20949
Check github action result for main branch
Change-Id: I70fcdaa3bb3802a77a9eb3fbd6e80c9690cc4ed1

feat: add zip files for github.io release

---

build/dockerfiles/entrypoint.sh

there is a link that is not updated
https://github.com/eclipse/che/issues/19906
look at generated links
Change-Id: I4c094c55197e03513074a925f1356cb17639fe30

fix: Fix invalid link for che-code devWorkspaces

---

dockerfiles/rust-1.57/Dockerfile

Adds Dockerfile for Rust version 1.57
eclipse/che#20952
- The test platform: PizzaFactory/Camino https://che-banco.camino.pizzafactory.jp/dashboard/
- Installation method: Helm chart.
- steps to reproduce: Run build.sh in this repository.
devfile.yaml for Rust will be fixed after this PR is merged (and Docker image is pushed.)

feat: Add the Dockerfile for Rust-1.57.

---

.github/dependabot.yml
.github/workflows/next-build.yml
.github/workflows/pr-checks.yml

Update github action checkout + introduce dependabot to check for new versions
Fixes https://github.com/eclipse-che/che-devfile-registry/issues/559
Fixes https://github.com/eclipse-che/che-devfile-registry/issues/560
Fixes https://github.com/eclipse-che/che-devfile-registry/issues/561
Check github actions result

Bump dependencies

---

deploy/kubernetes/che-devfile-registry/templates/deployment.yaml
deploy/kubernetes/che-devfile-registry/values.yaml

Enables to set `affinity:` via Helm.
No issue related.
- Modify `values.yaml`.
- Run `helm lint`

feat:[helm] Enable to set `affinity:`.

---

README.md

Adding the contribute badge to README.md

chore: Adding the contribute badge to README.md

---

.github/CODEOWNERS

Remoe jpinkney from codeowners

chore: Remove jpinkney from codeowners

---

devfiles/apache-camel-k/meta.yaml
devfiles/apache-camel-springboot/meta.yaml
devfiles/bash/meta.yaml
devfiles/che4z/meta.yaml
devfiles/cpp/meta.yaml
devfiles/dotnet-asp.net/meta.yaml
devfiles/dotnet/meta.yaml
devfiles/go/meta.yaml
devfiles/java-gradle/meta.yaml
devfiles/java-lombok/meta.yaml
devfiles/java-maven/meta.yaml
devfiles/java-mongo/meta.yaml
devfiles/java-mysql/meta.yaml
devfiles/java-web-spring/meta.yaml
devfiles/java-web-vertx/meta.yaml
devfiles/nodejs-angular/meta.yaml
devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs-react/meta.yaml
devfiles/nodejs-yarn/meta.yaml
devfiles/nodejs/meta.yaml
devfiles/php-laravel/meta.yaml
devfiles/php-mysql/meta.yaml
devfiles/php-symfony/meta.yaml
devfiles/php-web-simple/meta.yaml
devfiles/python-django/meta.yaml
devfiles/python/meta.yaml
devfiles/quarkus-command-mode/meta.yaml
devfiles/quarkus/meta.yaml
devfiles/rust/meta.yaml
devfiles/scala-sbt/meta.yaml

chore: gh20976 switch to uppercase Community instead of community
Change-Id: I406520621bf3ab6a775b8f94780e28a97ba041ff
N/A
N/A

chore: gh20976 switch to uppercase Community instead of community

---

devfiles/go/meta.yaml

Change the sample in Go devfile v2, since previous one is broken.
https://github.com/eclipse/che/issues/20686
Run the workspace by https://github.com/che-samples/golang-example/tree/devfilev2 and check that all commands and go plugin work as expected. 

chore:update devfile v2 link for Go

---

devfiles/apache-camel-springboot/meta.yaml

Applies proper link to the sample for apache-camel-springboot stack
No issue, just a tiny fix.

chore: update link to devfilev2 sample

---

devfiles/cpp/meta.yaml
devfiles/nodejs-angular/meta.yaml
devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs-react/meta.yaml
devfiles/nodejs-yarn/meta.yaml
devfiles/nodejs/meta.yaml

spelling fix for meta.yaml files containing mentions of Node.js
https://issues.redhat.com/browse/RHDEVDOCS-4300

rhdevdocs-4300 spelling fix

---

.github/workflows/next-build.yml
README.md

chore: #21790 add badges for some actions and a link to downstream 3.x job
Change-Id: Ia856fcf1f78f3f966c8be0526214107f5162d16b
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
N/A

chore: #21790 add badges for some actions and a link to downstream 3.x job

---

build/dockerfiles/entrypoint.sh

chore: theia/next is dead, remove it (part 2)
Change-Id: I7e4f91dd5350a37850e26013e8c623f2039460cd
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
https://github.com/eclipse/che/issues/21814
continued from https://github.com/eclipse-che/che-devfile-registry/pull/685
N/A

chore: theia/next is dead, remove it (part 2)

---

.github/workflows/build-sidecar-images-on-push.yml
.github/workflows/check-sidecar-image-digests.yml
.github/workflows/next-build.yml
.github/workflows/pr-checks.yml
.github/workflows/release.yml
.github/workflows/try-in-web-ide.yaml

Signed-off-by: sdawley <sdawley@redhat.com>
Updates Ubuntu version in GitHub actions to be 22.04 so it's consistent with other che actions.
https://github.com/eclipse/che/issues/21763

chore: Update Ubuntu to 22.04

---

.ci/cico-devfile-pr-test.sh
.ci/installation-util.sh
tools/devworkspace-generator/package.json

Updates version of che-devworkspace-generator tool

chore: cleanup version of devworkspace-generator tool

---

happy-path/Dockerfile

use the same version of spring-petclinik project as in happy-path https://github.com/eclipse/che/blob/main/tests/e2e/files/happy-path/happy-path-workspace.yaml#L10
Trying to fix https://github.com/eclipse-che/che-devfile-registry/actions/runs/3748256409/jobs/6365391611

chore: use the same version of spring-petclinik project as in happy-path

---

.github/workflows/devworkspace-generator-publish-next.yml

Add GH action to publish devworkspace-generator tool on npm registry

chore: add GH action to publish devworkspace-generator tool

---

build.sh
build/dockerfiles/Dockerfile
build/scripts/generate_devworkspace_templates.sh

Generates DevWorkspaces at the docker build

chore: move devworkspace generation into Dockerfile

---

tools/devworkspace-generator/README.md

add README.md for devworkspace-geneator tool

chore: add README.md for devworkspace-geneator tool

---

devfiles/apache-camel-k/meta.yaml
devfiles/apache-camel-springboot/meta.yaml
devfiles/bash/meta.yaml
devfiles/cpp/meta.yaml
devfiles/dotnet-asp.net/meta.yaml
devfiles/go/meta.yaml
devfiles/java-lombok/meta.yaml
devfiles/java-mongo/meta.yaml
devfiles/java-web-spring/meta.yaml
devfiles/nodejs-angular/meta.yaml
devfiles/nodejs-mongo/meta.yaml
devfiles/nodejs-react/meta.yaml
devfiles/nodejs-yarn/meta.yaml
devfiles/nodejs/meta.yaml
devfiles/php-symfony/meta.yaml
devfiles/python-django/meta.yaml
devfiles/python/meta.yaml
devfiles/quarkus/meta.yaml
devfiles/rust/meta.yaml
devfiles/scala-sbt/meta.yaml

Updates links to the samples sources to fetch devfiles from the main branch
https://github.com/eclipse/che/issues/21926
- build the image by running **build.sh** script
- check that DevWorkspaces were generated for all samples in the `/usr/local/apache2/htdocs/devfiles/` folder 

chore: Use main branch of a sample repo to fetch a devfile

---

tools/devworkspace-generator/src/main.ts
tools/devworkspace-generator/tests/main.spec.ts

Signed-off-by: Oleksii Orel <oorel@redhat.com>
Add axiosInstance as a parameter into generateDevfileContex method.

Add axiosInstance as a parameter into generateDevfileContex method

---

tools/devworkspace-generator/src/main.ts
tools/devworkspace-generator/tests/main.spec.ts

Add an ```editorContent``` as a parameter into the ```generateDevfileContex``` method.
It needs for https://github.com/eclipse/che/issues/21563

Add an editorContent as a parameter into generate method

---

devfiles/dotnet-asp.net/meta.yaml

Updates a sample for .NET to use one that supports .NET6.0
https://github.com/eclipse/che/issues/22077
- Start a workspace using https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#/https://github.com/che-samples/dotnet-web-simple
- Try to run devfile's tasks
- Check that C# extension provides functionality (like code completion, error hilighting)  

chore: replace .Net sample that supports .Net 6.0

---

.github/workflows/devworkspace-generator-publish-next.yml
.github/workflows/next-build.yml
.github/workflows/pr-checks.yml

replace deprecated set-output in GH actions
https://github.com/eclipse/che/issues/21993

chore: che-21993 replace deprecated set-output in actions

---

tools/devworkspace-generator/src/github/github-resolver.ts
tools/devworkspace-generator/src/github/github-url.ts
tools/devworkspace-generator/tests/github/github-resolver.spec.ts

Extend the github url pattern to accept GitHub enterprise urls like `https://github.<company name>.com`.
fixes https://github.com/eclipse/che/issues/22105

Add Github Enterprise repositories support

---

build/scripts/generate_devworkspace_templates.sh

bump evworkspace generator tool from 0.0.1-c8bd5c0 to 0.0.1-638fadc
https://github.com/eclipse/che/issues/22149

feat: bump devworkspace generator tool

---

tools/devworkspace-generator/src/generate.ts
tools/devworkspace-generator/tests/generate.spec.ts

This PR fixed the creation flow for the DevWorkspace metadata.
https://github.com/eclipse/che/issues/22193

Fix the creation flow for the DevWorkspace metadata

---

build/scripts/generate_devworkspace_templates.sh
tools/devworkspace-generator/src/main.ts

* Update devworkspace-generator version
* Remove redundant import

Update devworkspace-generator version

---

build.sh
build/dockerfiles/Dockerfile
build/scripts/generate_devworkspace_templates.sh

Use plugin registry URL with the specific version when generating devworkspaces.
It is needed to grab the correct version of the editor when the release is happening. 
https://github.com/eclipse/che/issues/22340
See PR checks

fix: specify plugin registry url for generating DWs

---

build/dockerfiles/entrypoint.sh

fix: Replaces images with digests in case the actual image is locates on the next line.
```
image: >-
quay.io/defile/.....
```
N/A
https://github.com/eclipse/che/issues/21445
N/A

fix: Replaces images with digests

---

build/dev/build-devfile-registry.sh
build/dockerfiles/Dockerfile
build/dockerfiles/rhel.Dockerfile

chore: devfile registry should return index file by /index path
N/A
https://github.com/eclipse/che/issues/22454
1. Build image with `./build.sh`
2. Check `index` existence by : `podman run -ti quay.io/eclipse/che-devfile-registry:next cat htdocs/index`

chore: devfile registry should return index file by `/index` path

---

.github/workflows/devworkspace-generator-release.yml

Add missing configuration for node setup (that authenticates for publishing of the project)

fix: fix dwo generator publishing

---

make-release.sh

properly update version of devworkspace generator

fix: fix dwo generator version update

---

tools/devworkspace-generator/package.json

Remove own che-devworkspace-generator dependency

chore: remove redundant dependency

---

tools/devworkspace-generator/package.json
tools/devworkspace-generator/src/generate.ts
tools/devworkspace-generator/yarn.lock

Bump @devfile/api version to 2.2.2-1700686170
https://github.com/eclipse/che/issues/22658
Check PR check that builds the project 

chore: bump @devfile/api to 2.2.2-1700686170

---

devfiles/apache-camel-k/meta.yaml
devfiles/apache-camel-springboot/meta.yaml

* Camel K devfiles is no more working
* Camel on Springboot still relies on a very old Camel version which is no more community supported.
There are nobody with time allocated to maintain these examples. They would benefit from drastic changes given new orientations on Camel. So removing for now and when we find people with time to work on it we can re-add some later.
There is also mention of Fuse which is the product and that will be EOL soon.

Remove outdated Camel devfiles

---

tools/devworkspace-generator/package.json
tools/devworkspace-generator/yarn.lock

Upgrade libraries.
It needs for https://github.com/eclipse-che/che-dashboard/pull/1115

fix: upgrade devfile/api and axios libs

---

tools/devworkspace-generator/src/api/devfile-context.ts
tools/devworkspace-generator/src/devfile-schema/2.3.0/devfile.json
tools/devworkspace-generator/src/devfile-schema/devfile-schema-validator.ts
tools/devworkspace-generator/tests/_data/devfile/2.3.0/empty-devfile.yaml
tools/devworkspace-generator/tests/_data/devfile/2.3.0/quarkus-api-devfile.yaml
tools/devworkspace-generator/tests/devfile-schema/devfile-schema-validator.spec.ts

Add new `2.3.0` devfile schema.
https://github.com/eclipse-che/che/issues/22997
1. Go to `tools/devworkspace-generator`
2. Execute `yarn && yarn build` to build the tool with the latest schema version.
3. Execute 
```
node lib/entrypoint.js --devfile-url:https://github.com/vinokurig/test.git --editor-entry:che-incubator/che-code/latest --output-file:devworkspace-che-code-latest.yaml
```
See: the yaml file is successfully generated from the `2.3.0` devfile.

Support Devfile 2.3.0
